### ISSUE TITLE
Allow passing `Promise` to `data.promise` instead of `() => Promise<any>`

### ISSUE THREAD

**Issue by skoshx** [emilkowalski/sonner#1]
First of all, great work, looks amazing and has a delightful user experience!!

One thing is, I would like to be able to use the toast like this:
```typescript

const promise = settingsMutation.mutate(...)

toast('Your settings have been updated', { promise })

```

Instead of writing it like this, since often times the mutation can have quite a bit of code inside, so wrapping it all with the toast feels unergonomic.
```typescript
toast('Your settings have been updated', { promise() {
  return settingsMutation.mutate(...)
}}
```

If you feel like this is a reasonable change, I would be glad to submit a Pull Request!

**Comment by emilkowalski** [comment]
I like this, feel free to submit a PR!
