### ISSUE TITLE
Use anywhere

### ISSUE THREAD

**Issue by Steellgold** [emilkowalski/sonner#107]
I'd like to have in one place (example a layout.tsx)

```TSX
<Toaster position="top-right" expand toastOptions={{
  style: {
    backgroundColor: "#1F2937",
    color: "#fff",
    border: "1px solid #4B5563"
  }
}} />
```

Then, where I needed it, I used

```tsx
toast("Copied to clipboard!", ...
```

But it doesn't work

I tested several tricks, to put it without custom style, just <Toaster />. 

In a page.tsx, a layout.tsx nothing works

If I put it where I use toast(), on the other hand, it works.
The only solution I can think of is to create a component that has my styles inside it, so that if I modify it, it modifies everything.

**Comment by emilkowalski** [comment]
`<Toaster />` needs to be used inside a client component. It's on my list to make it work inside a server component.
