### ISSUE TITLE
Unable to create a loading Toast

### ISSUE THREAD

**Issue by timscullin** [emilkowalski/sonner#113]
Hey Emil.

Thanks for the making the most beautiful toast lib! 

I have a small request, currently the only way to generate toast with a pending state and get the nice Loader icon is to provide a promise.
It would be awesome if you could generate a loading state toast which could be closed manually.

eg:

```
const toastId = toast.loading('Doing something spectacular');
await someAsyncFunction();
toast.success('Toast has been updated', {
  id: toastId,
});
```

Thanks again!

**Comment by emilkowalski** [comment]
Added in #122

**Comment by timscullin** [comment]
Amazing thank you!
