### ISSUE TITLE
Add `finally` property to `toast.promise`

### ISSUE THREAD

**Issue by ajmnz** [emilkowalski/sonner#117]
👋

Any chance we can get a `finally` property in `toast.promise` that gets called when the promise either resolves or rejects? I think this will close the circle on promise handling since we already have `success` (for `then`) and `error` (for `catch`).

```ts
toast.promise(
  () => apiCall({ foo: "bar" }),
  {
    loading: "Loading...",
    success: "Updated!",
    error: "Error updating",
    finally: () => {
      refetch(["myQuery"])
    }
  }
);
```

I'm open to make a PR if needed. Thank you!

**Comment by emilkowalski** [comment]
Yup, we can add it, feel free to make a PR!

**Comment by ajmnz** [comment]
> Yup, we can add it, feel free to make a PR!

Done! #118
