### ISSUE TITLE
Can i get the count on the right top of the collapsed toast?

### ISSUE THREAD

**Issue by NaveenkumarMD** [emilkowalski/sonner#120]
I would like to have the number of toasts that are collapsed in top right corner of the collapsed section.Is it supported

**Comment by emilkowalski** [comment]
What do you mean? Do you want to get the number of all toasts?

**Comment by emilkowalski** [comment]
Closing for now, feel free to re-open and let me know what your goal is

**Comment by NaveenkumarMD** [comment]
Yeah the number of toasts available at the moment. Tackled this by having a mutation observer. https://medium.com/@naveen9715568487/how-i-added-counter-to-sonner-a-react-toast-package-a08334694a08.
The package is amazing.
