### ISSUE TITLE
Disallow user to dismiss toast until some action is completed

### ISSUE THREAD

**Issue by emigdio821** [emilkowalski/sonner#125]
Hi, not an issue but a question. Is it possible to keep a toast alive until I remove it programmatically? 
I'm currently using `duration: Infinity` but when I slide the toast down it gets dismissed. 

Thanks in advance!

**Comment by emilkowalski** [comment]
What's the use case?

**Comment by emigdio821** [comment]
I'm working on a component to record audio, so I want to display the toast with a status of "Recorded..."  and I don't want this toast to be dismissible until the audio is finished recording. If I swipe the toast down it will be dismissed, same for the "x" button. I would like to disable this option. I mean, keep the toast in the screen until I remove it by using 
`toast.dismiss()` or `toast.dismiss('myToastId')`

**Comment by emilkowalski** [comment]
You can add dismissible prop now, it has been added in #131

**Comment by michaelhays** [comment]
I wasn't able to click links within my toast until I set `dismissible: false`, probably because the toast drag interaction was taking precedence over the click. May be worth documenting somewhere
