### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getTime')

### ISSUE THREAD

**Issue by dzungmv** [emilkowalski/sonner#127]
I created simple Promise like a docs:
    toast.promise(() => new Promise((resolve) => setTimeout(resolve, 2000)), {
      loading: 'Loading',
      success: 'Success',
      error: 'Error',
    });
but when it pending, I try click to loading icon, So this error here: "TypeError: Cannot read properties of null (reading 'getTime')".

I use nextjs 13 latest 13.4,19

**Comment by emilkowalski** [comment]
This should be fixed in #129
