### ISSUE TITLE
More than one Toaster with different positions

### ISSUE THREAD

**Issue by CriticalNameError** [emilkowalski/sonner#132]
Hello!

For my use case, I'd need a toaster with position bottom-center and one with top-center. However, when I create two Toaster components, they are synchronized and I do not find a handle to specify a "target toaster" when calling toast(...). Is there such functionality already and I just didn't find it? Could this be added to the roadmap?

Best regards!

**Comment by 7iomka** [comment]
We all need the option to override / set position on toast instance call

Like in the popular libraries like https://fkhadra.github.io/react-toastify/positioning-toast
