### ISSUE TITLE
The requested module 'sonner' does not provide an export named 'Toaster'

### ISSUE THREAD

**Issue by danestves** [emilkowalski/sonner#135]
I'm using ESM and with the latest version of `sonner` it seems that the exports are not working 🤔 

![](https://github.com/emilkowalski/sonner/assets/31737273/a432327e-cc66-423b-bea6-ace78313f21d)

**Comment by emilkowalski** [comment]
Please update to `0.7.4`, I've just pushed a fix. Sorry about that!

**Comment by danestves** [comment]
Working again, thanks!
