### ISSUE TITLE
Swipe to dismiss on mobile

### ISSUE THREAD

**Issue by skittlesaur** [emilkowalski/sonner#141]
I have been playing with Sonner for some time and it's amazing. One thing i have noticed is that i frequently attempt to swipe the toast off the screen to dismiss it on mobile. It seems like a thing an average user would expect so, for a better ux, it should be implemented as a feature of Sonner.

**Comment by emilkowalski** [comment]
Wdym? You can swipe it down to dismiss on mobile.

**Comment by skittlesaur** [comment]
> Wdym? You can swipe it down to dismiss on mobile.

Oh, I have tested it on the docs site and it doesn't seem to be working on Safari (iOS)

**Comment by skittlesaur** [comment]
> Wdym? You can swipe it down to dismiss on mobile.

Oh, i didn't know that, i thought i was supposed to swipe it to some horizontal side (left/right) to dismiss it. Just like the fact that most notification stacks are dismissible by side unless there's a single popup notification.

Looks amazing though!
