### ISSUE TITLE
Disable `promise.loading`?

### ISSUE THREAD

**Issue by joelmoss** [emilkowalski/sonner#142]
I want to be able to disable the loading state of a promise, but passing `false` as its value doesn't seem to work - the loading toast is still shown.

```js
toast.promise(myPromise, {
  loading: false,
  success: 'Success`,
  error: 'Error'
});
```

How can I disable the loading state?

thx

**Comment by joelmoss** [comment]
Same applies to the `success` and `error` states actually 😏

**Comment by skittlesaur** [comment]
Seems unnecessary since you can try and catch the promise and call toast based on it

**Comment by joelmoss** [comment]
Well of course (and that is what I am doing), but if that's the general way of thinking, then you could argue that `toast.promise()` is also unnecessary 😏

**Comment by skittlesaur** [comment]
> Well of course (and that is what I am doing), but if that's the general way of thinking, then you could argue that `toast.promise()` is also unnecessary 😏

Not really, the whole idea of `toast.promise` is that it modifies the current promise to some new state after the loading is complete. It's a shortcut to getting a toast id and manually modifying it. So it's pretty useful. Using a try and catch for your case is simple enough and doesn't add any complexity to the code

**Comment by emilkowalski** [comment]
> Well of course (and that is what I am doing), but if that's the general way of thinking, then you could argue that `toast.promise()` is also unnecessary 😏

Out of curiosity - what's your use case for a promise toasting without a loading state?
