### ISSUE TITLE
Add Tailwind styling support

### ISSUE THREAD

**Issue by Lucasmm016** [emilkowalski/sonner#143]
Add support for Tailwind styling through className, example:
```
const t = () => toast.success('Success!', {
     className: 'bg-indigo-500'
   })
```

Reason: Makes it easier for those who use the lib in Next 13!

**Comment by emilkowalski** [comment]
This is already added.

**Comment by Lucasmm016** [comment]
And how do I style toast with tailwind? I'm using it with Next 13.

**Comment by emilkowalski** [comment]
https://sonner.emilkowal.ski/toast#headless

or just className like here https://sonner.emilkowal.ski/toast#rendering-the-toast
