### ISSUE TITLE
How to pass options to headless toasts....

### ISSUE THREAD

**Issue by ames20** [emilkowalski/sonner#149]
I couldn't find any reference in the documentation as to how to pass options, e.g. duration, to individual toasts when using toast.custom....could you let me know where I could find the info? Thanks so much

**Comment by Gabrieltrinidad0101** [comment]
URL: https://sonner.emilkowal.ski/toast

Property | Description | Default
-- | -- | --
description | Toast's description, renders underneath the title. | -
closeButton | Adds a close button which shows on hover. | false
invert | Dark toast in light mode and vice versa. | false
important | Control the sensitivity of the toast for screen readers | false
duration | Time in milliseconds that should elapse before automatically closing the toast. | 4000
position | Position of the toast. | bottom-right
dismissible | If false, it'll prevent the user from dismissing the toast. | true
icon | Icon displayed in front of toast's text, aligned vertically. | -
action | Renders a primary button, clicking it will close the toast. | -
cancel | Renders a secondary button, clicking it will close the toast. | -
id | Custom id for the toast. | -
onDismiss | The function gets called when either the close button is clicked, or the toast is swiped. | -
onAutoClose | Function that gets called when the toast disappears automatically after it's timeout (duration` prop). | -

**Comment by emilkowalski** [comment]
Like this `toast.custom(() => <div>custom</div>, { duration: 5000 });`

**Comment by victorbadaro** [comment]
> Like this `toast.custom(() => <div>custom</div>, { duration: 5000 });`

Is it possible to pass them (options) to the components that will be rendered?
Something like this (or in any other way):
```jsx
toast.custom((t) => <CustomToast duration={t.somethingToGetDuration}>...</CustomToast>);
```
It would be nice because the `<CustomToast />` might need this prop to render a progress bar for example...
