### ISSUE TITLE
Typescript module resolution "Bundler" types

### ISSUE THREAD

**Issue by JClackett** [emilkowalski/sonner#154]
When setting module resolution to "Bundler" typescript can't find the types for this library, they need to be explicitly written in the exports field in the package json I think:

when I update it to this:

```json
"exports": {
    "import": {
      "default": "./dist/index.mjs",
      "types": "./dist/index.d.ts"
    },
    "require": {
      "default":  "./dist/index.js",
      "types": "./dist/index.d.ts"
    }
 },
```

Everything works, so will use patch-package in the meantime, would be great if sonner could update!

Im also not an expert at js module stuff so could be missing something, but the above worked for me :)

**Comment by emilkowalski** [comment]
Fixed in #161
