### ISSUE TITLE
Incorrect links inside documentation pages

### ISSUE THREAD

**Issue by ehtishamsajjad1** [emilkowalski/sonner#159]
The "Edit this page" link on the https://sonner.emilkowal.ski/getting-started page points to the wrong URL. The link currently points to https://github.com/emilkowalski/sonner/src/pages/getting-started.mdx, which is not a valid URL. The correct URL should include the tree/main path segment, like this: https://github.com/emilkowalski/sonner/tree/main/src/pages/getting-started.mdx.

Please update the link to point to the correct URL.

**Comment by emilkowalski** [comment]
Fixed in #162
