### ISSUE TITLE
Make `PromiseData` partial in `toast.promise`

### ISSUE THREAD

**Issue by ajmnz** [emilkowalski/sonner#160]
👋

We use Sonner together with React Query. Our `queryClient` automatically shows an error toast when a request fails (and some other cond. are met). When making mutations, we use `toast.promise` to show the `loading` and `success` states — since errors are handled elsewhere, we don't even bother.

What I'm proposing is changing `PromiseData`

```ts
<ToastData>(promise: PromiseT<ToastData>, data?: PromiseData<ToastData>) => string | number;
```

To the following:

```ts
<ToastData>(promise: PromiseT<ToastData>, data?: Partial<PromiseData<ToastData>>) => string | number;
```

This would not only make `error` optional, but all the other properties too.

I'm open to make a PR if needed. Thank you!

**Comment by emilkowalski** [comment]
Sounds good, feel free to post a PR!

**Comment by iambpn** [comment]
Seems easy. Is this PR already assigned by anybody? If not, can you assign this to me?

First time trying to submit a PR so little guidance would be great.
