### ISSUE TITLE
toast does not work in useEffect or useLayoutEffect 

### ISSUE THREAD

**Issue by X-Vneer** [emilkowalski/sonner#168]
I have a multi step registration form , each step has its own page, i have a context to store data for each step and share it.
for a better user experience i want to make sure in each step the context has a validate data from previous setp if NOT i shoud send user back to previous step and alert him for not having complete or valid data.

this is a snapshot of the code i have

btw it works when i put it inside a setTimeout 

![toast](https://github.com/emilkowalski/sonner/assets/100439355/10f8d978-a776-45f0-bdd5-c880686fc2ad)

**Comment by hkbertoson** [comment]
Why not just validate it before they leave the page?

**Comment by emilkowalski** [comment]
> I have a multi step registration form , each step has its own page, i have a context to store data for each step and share it. for a better user experience i want to make sure in each step the context has a validate data from previous setp if NOT i shoud send user back to previous step and alert him for not having complete or valid data.
> 
> this is a snapshot of the code i have
> 
> btw it works when i put it inside a setTimeout
> 
> ![toast](https://user-images.githubusercontent.com/100439355/272859094-10f8d978-a776-45f0-bdd5-c880686fc2ad.png)

Works fine for me, can you provide a codesandbox demo?

**Comment by X-Vneer** [comment]
> Why not just validate it before they leave the page?

I actually do validate it before sending user to second step, but what if the user refreshed the second page or just landed on the second page by accident

**Comment by X-Vneer** [comment]
This is a codesandbox demo i hope i properly set it up,


https://codesandbox.io/p/github/X-Vneer/mabet-partners-sonner-test/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clnedt1jh00073n6hlhjy3amc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clnedt1jh00033n6hy9yhee8v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clnedt1jh00053n6hc69zdmoz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clnedt1jh00063n6hqhh3uifw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clnedt1jh00033n6hy9yhee8v%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00033n6hy9yhee8v%2522%252C%2522activeTabId%2522%253A%2522clnedu5kh00c43n6hkk4edqj9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnedt1jh00023n6hfj54megt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clnedu5kh00c43n6hkk4edqj9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clnedt1jh00063n6hqhh3uifw%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00063n6hqhh3uifw%2522%252C%2522activeTabId%2522%253A%2522clnedui7g00dq3n6hekeku87d%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clnedttzf009g3n6hbtlshgw6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3001%252C%2522id%2522%253A%2522clnedui7g00dq3n6hekeku87d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fsignup%252Fregister%2522%257D%255D%257D%252C%2522clnedt1jh00053n6hc69zdmoz%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00053n6hc69zdmoz%2522%252C%2522activeTabId%2522%253A%2522clnedt1jh00043n6hl8916xsk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnedt1jh00043n6hl8916xsk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clnedt4xw001me6ghboq9fg9c%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clnedtrn1007x3n6hh0cf5gwm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

you should go to **/signup/register**

**Comment by veerbal1** [comment]
Hello @X-Vneer Have you resolved your issue or is it still pending?

**Comment by veerbal1** [comment]
> Why not just validate it before they leave the page?

Yes

**Comment by X-Vneer** [comment]
> Hello @X-Vneer Have you resolved your issue or is it still pending?

I actually worked around it by putting it in a **setTimeout** but still don't know why it would not work just fine without a **setTimeout**

**Comment by emilkowalski** [comment]
> This is a codesandbox demo i hope i properly set it up,
> 
> https://codesandbox.io/p/github/X-Vneer/mabet-partners-sonner-test/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clnedt1jh00073n6hlhjy3amc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clnedt1jh00033n6hy9yhee8v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clnedt1jh00053n6hc69zdmoz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clnedt1jh00063n6hqhh3uifw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clnedt1jh00033n6hy9yhee8v%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00033n6hy9yhee8v%2522%252C%2522activeTabId%2522%253A%2522clnedu5kh00c43n6hkk4edqj9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnedt1jh00023n6hfj54megt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clnedu5kh00c43n6hkk4edqj9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clnedt1jh00063n6hqhh3uifw%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00063n6hqhh3uifw%2522%252C%2522activeTabId%2522%253A%2522clnedui7g00dq3n6hekeku87d%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clnedttzf009g3n6hbtlshgw6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3001%252C%2522id%2522%253A%2522clnedui7g00dq3n6hekeku87d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fsignup%252Fregister%2522%257D%255D%257D%252C%2522clnedt1jh00053n6hc69zdmoz%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00053n6hc69zdmoz%2522%252C%2522activeTabId%2522%253A%2522clnedt1jh00043n6hl8916xsk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnedt1jh00043n6hl8916xsk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clnedt4xw001me6ghboq9fg9c%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clnedtrn1007x3n6hh0cf5gwm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
> 
> you should go to **/signup/register**

This demo is broken.

**Comment by hkbertoson** [comment]
> > Why not just validate it before they leave the page?
> 
> I actually do validate it before sending user to second step, but what if the user refreshed the second page or just landed on the second page by accident

Store the values in State.

**Comment by X-Vneer** [comment]
> > This is a codesandbox demo i hope i properly set it up,
> > https://codesandbox.io/p/github/X-Vneer/mabet-partners-sonner-test/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clnedt1jh00073n6hlhjy3amc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clnedt1jh00033n6hy9yhee8v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clnedt1jh00053n6hc69zdmoz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clnedt1jh00063n6hqhh3uifw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clnedt1jh00033n6hy9yhee8v%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00033n6hy9yhee8v%2522%252C%2522activeTabId%2522%253A%2522clnedu5kh00c43n6hkk4edqj9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnedt1jh00023n6hfj54megt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clnedu5kh00c43n6hkk4edqj9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clnedt1jh00063n6hqhh3uifw%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00063n6hqhh3uifw%2522%252C%2522activeTabId%2522%253A%2522clnedui7g00dq3n6hekeku87d%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clnedttzf009g3n6hbtlshgw6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3001%252C%2522id%2522%253A%2522clnedui7g00dq3n6hekeku87d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fsignup%252Fregister%2522%257D%255D%257D%252C%2522clnedt1jh00053n6hc69zdmoz%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00053n6hc69zdmoz%2522%252C%2522activeTabId%2522%253A%2522clnedt1jh00043n6hl8916xsk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnedt1jh00043n6hl8916xsk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clnedt4xw001me6ghboq9fg9c%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clnedtrn1007x3n6hh0cf5gwm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
> > you should go to **/signup/register**
> 
> This demo is broken.

sorry for that, i'm sure i noted that you need to navigate to **signup/register ** 


btw this should be navigated to the proper path
https://codesandbox.io/p/github/X-Vneer/mabet-partners-sonner-test/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clnedt1jh00073n6hlhjy3amc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clnedt1jh00033n6hy9yhee8v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clnedt1jh00053n6hc69zdmoz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clnedt1jh00063n6hqhh3uifw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clnedt1jh00033n6hy9yhee8v%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00033n6hy9yhee8v%2522%252C%2522activeTabId%2522%253A%2522clnedu5kh00c43n6hkk4edqj9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnedt1jh00023n6hfj54megt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clnedu5kh00c43n6hkk4edqj9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clnedt1jh00063n6hqhh3uifw%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00063n6hqhh3uifw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clnedttzf009g3n6hbtlshgw6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fsignup%252Fregister%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clnedttzf009g3n6hbtlshgw6%2522%257D%252C%2522clnedt1jh00053n6hc69zdmoz%2522%253A%257B%2522id%2522%253A%2522clnedt1jh00053n6hc69zdmoz%2522%252C%2522activeTabId%2522%253A%2522clnedt1jh00043n6hl8916xsk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnedt1jh00043n6hl8916xsk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clnfyyxsu001ye6gh75nm550v%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clnedtrn1007x3n6hh0cf5gwm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by X-Vneer** [comment]
see the **src/app/(app)/(auth)/signup/register/page.tsx** file

**Comment by emilkowalski** [comment]
What are the steps to reproduce? This codesandbox looks like an app, I don't know what to do in order to reproduce the issue you described.

**Comment by X-Vneer** [comment]
> What are the steps to reproduce? This codesandbox looks like an app, I don't know what to do in order to reproduce the issue you described.

Sorry for the late reply 

It's supposed to alet the user on page load (show a sonner notification)

**Comment by DennisKraaijeveld** [comment]
I think I have something similar. On redirect the Toast is on the bottom of the screen without any styles applied. 

```
export function EpicToaster({ toast }: { toast?: Toast | null }) {
	return (
		<>
			<Toaster closeButton position="top-center" />
			{toast ? <ShowToast toast={toast} /> : null}
		</>
	)
}

function ShowToast({ toast }: { toast: Toast }) {
	const { id, type, title, description } = toast
	useEffect(() => {
		setTimeout(() => {
			showToast[type](title, { id, description })
		}, 0)
	}, [description, id, title, type])
	return null
}
```

Try to get a reproduction asap.

**Comment by viczaca** [comment]
@X-Vneer I had this exact problem using react-hot-toast. Instead of using setTimeout you can change the order of components in your layout. First the Toaster (the one that renders all the toasts) and then your children (the one with the useEffect).

I think the problem is caused by adding a toast in the useEffect (when Page loads) before the Toaster is even rendered. With setTimeout you are queueing the add toast function at the end of the current JavaScript event stack, so it executes after the Toaster renders.

**Comment by emilkowalski** [comment]
@viczaca This is the solution, please use this in case you are expieriencing this problem. I don't think we can do anything about it on the library level atm.

**Comment by junwen-k** [comment]
> @X-Vneer I had this exact problem using react-hot-toast. Instead of using setTimeout you can change the order of components in your layout. First the Toaster (the one that renders all the toasts) and then your children (the one with the useEffect).
> 
> I think the problem is caused by adding a toast in the useEffect (when Page loads) before the Toaster is even rendered. With setTimeout you are queueing the add toast function at the end of the current JavaScript event stack, so it executes after the Toaster renders.

Amazing, I've been scratching my head over this and it appears that this is the solution! (This only happen on next build but not next dev)

Rendering `<Toaster />` before the component that uses `useEffect` is the fix.

Should we include this caveat in the documentation in case someone stumbled across the same issue, maybe something like

---

### Usage within useEffect

Ensure that `<Toaster />` is rendered before the component that use `toast()` within `useEffect()`.

For more information, see this [issue](https://github.com/emilkowalski/sonner/issues/168).

```jsx

// ...

function App() {
  return (
    <div>
      <Toaster />
      <ToastEffect />
    </div>
  );
}
```

**Comment by rohitt-gupta** [comment]
@viczaca you saved me a hell lot of time, having already wasted 12-13 hours, now it is fixed.
Thank you from the bottom of my heart.
