### ISSUE TITLE
Option for disabling auto styling

### ISSUE THREAD

**Issue by baumerdev** [emilkowalski/sonner#177]
There are some some closed issues regarding custom styling/theming, e.g. #143 or #171

The problem is, if you add classes via className those will be added to the toast but the default styles usually overwrite those styles since the are more specific. So you have to always use important for every property that's included in the default styles.

The default styling is only disabled if you provide a "jsx" via `custom()`method. But with that you aren't able to use Promises since they exclude each other.

I propose to introduce a new config variable like `unstyled?: boolean`. If set to true the `data-styled` on the `<li>` value won't be set to true.
https://github.com/emilkowalski/sonner/blob/main/src/index.tsx#L214C7-L214C40

**Comment by emilkowalski** [comment]
Added in #187
