### ISSUE TITLE
How to set bidirectional offset? 

### ISSUE THREAD

**Issue by fax1ty** [emilkowalski/sonner#179]
Like `[40, 20]`, where 40 is vertical offset and 20 is horizontal

**Comment by SebastianKuesters** [comment]
This workaround (replace `offset` with `top` and `right` style) worked for us:

```tsx
<Toaster closeButton richColors position="top-right" style={{ top: 128, right: 32 }} />
```

**Comment by emilkowalski** [comment]
I'd like to keep that prop as is, let's use the solution @SebastianKuesters provided.
