### ISSUE TITLE
Add warning and info rich color toast

### ISSUE THREAD

**Issue by prasannakarki77** [emilkowalski/sonner#184]
Similar to rich color success and error toast message, add

warning - `toast.warn("toast message")` with yellow or orange color
info - `toast.info("toast message")` with blue or any other color

**Comment by mattpilleul** [comment]
Hi, done a fork to add them, if you want !

**Comment by emreakdas** [comment]
@prasannakarki77 @mattpilleul hey, I sent a pull request. I hope you liked the colors. #195
