### ISSUE TITLE
Support customizing action label style in toastOptions

### ISSUE THREAD

**Issue by MichaelYuhe** [emilkowalski/sonner#188]
When I try to change my toaster's background color to this, the action label background will be too similar
<img width="326" alt="image" src="https://github.com/emilkowalski/sonner/assets/63531512/00059f6e-7665-4226-9034-8b8edf07e4fb">
<img width="382" alt="image" src="https://github.com/emilkowalski/sonner/assets/63531512/496d312c-b565-42a7-9a59-fd2ea2b78d05">
Is there any options to customize action label background color?
If there is a plan for it, I would like to work on that!

**Comment by emilkowalski** [comment]
Added in #214
