### ISSUE TITLE
Change position based on device-width

### ISSUE THREAD

**Issue by jeanhdev** [emilkowalski/sonner#189]
I'd like to change the position based on the device. 

Indeed, on desktop - I use `bottom-right` but in my case - on mobile, if navigation is on the bottom (or for other reasons) - it can obfuscate the view so I'd like to use `top-left` (ie. top).

Currently, I make it work using `react-device-detect` (which parses the user agent strings) in my global `<Toaster />` provider.

PS. thanks for the package!

**Comment by emilkowalski** [comment]
Hey, thanks for the suggestion! Passing a different `position` prop based on device width is ok, I don't think we want to support this in the library itself as it's easily achievable by the consumers.
