### ISSUE TITLE
notifications stay visible

### ISSUE THREAD

**Issue by codeagencybe** [emilkowalski/sonner#190]
Hello

How can I make the notifications stay visible so they have to be closed manually? 
Maybe I'm misunderstanding some of the props in the docs, but anything I try will always auto close them, unless I hover over the notifications. 
I would like some notifications to remain visible unless you manually dismiss them so users can not miss important notifications.

**Comment by emilkowalski** [comment]
Set the duration to infinity like so:
toast("Hej", { duration: Infinity });

**Comment by jacob-orbiit** [comment]
> toast("Hej", { duration: Infinity });

@emilkowalski this doesn't work and actually causes the toast silently break / never appear (`<Toast duration={Infinity} />` causes the same adverse behaviour).

sonner `v1.3.1` (latest at the time of this post).
