### ISSUE TITLE
Cannot access toast.error on the server

### ISSUE THREAD

**Issue by stefanlogue** [emilkowalski/sonner#192]
I've got the latest version installed (1.0.4) and I've got the `<Toaster />` in a server component page. I now cannot call `toast.error()` from within a server component in order to see toasts. Is this expected behaviour? There doesn't seem to be any documentation around using the toast function in server components

**Comment by emilkowalski** [comment]
Toasts need to be called in client components, but Toaster can be mounted in a server component.
