### ISSUE TITLE
Got smaller paddings when there is 3 components in a row on mobile

### ISSUE THREAD

**Issue by pranavbabu** [emilkowalski/sonner#2]
![image](https://user-images.githubusercontent.com/54139019/220949160-85583934-ea80-4922-9654-0fce5a551eeb.png)

**Comment by emilkowalski** [comment]
Can't reproduce, which browser/device is this?

**Comment by adiletelf** [comment]
Redmi Note 8 Pro Android - everything works smoothly. I was delighted to know that dragging the toast to the side removes it and that all methods `toast`, `toast.error` are the same as in `react-hot-toast`. Switching between `react-hot-toast` and `Sonner` is easy. Starred ❤️

**Comment by joaom00** [comment]
I was able to reproduce when add a new toast while they are expanded

**Comment by bxb100** [comment]
Expand the toast and then random close the two of the bottom, then can reproduce same problem

Android + Firefox nightly

**Comment by joaom00** [comment]
Hey @pranavbabu and @bxb100, can you check if it was fixed in #7? 

https://sonner-git-fork-joaom00-patch-1-emilkowalski.vercel.app/
