### ISSUE TITLE
Updating loading toast is dismissed instantly

### ISSUE THREAD

**Issue by simbesh** [emilkowalski/sonner#201]
When creating a loading toast with `duration: infinite`, you must pass another duration in the update otherwise the update keeps the infinite duration. I would expect that the default duration should override the loading toasts duration.

However, when passing a new duration for the updated toast, it is not respected and closes instantly. (regardless of value set)

see: https://codesandbox.io/s/xenodochial-grass-jfsdrp?file=/src/App.js

**Comment by choeqq** [comment]
what would be an real world example of passing `duration: infinite`?

**Comment by simbesh** [comment]
Almost all instances where you need to control the loading toasts' state or an event that takes an indeterminate amount of time to complete.
If you don't set `duration: infinite` the loading toast will auto-close, after the default duration. (which I fail to see a use for)

my usage:
- long-running requests
- batch requests, grouped in one toast, updated with progress.

**Comment by emilkowalski** [comment]
This has been fixed in #206
