### ISSUE TITLE
No `info` or `warning` toasts

### ISSUE THREAD

**Issue by enchorb** [emilkowalski/sonner#203]
At https://sonner.emilkowal.ski/ examples for `info` and `warning` toasts are shown but the library does not have them

**Comment by emilkowalski** [comment]
Wdym by the library doesn't have them? You can call them with `toast.info`.

**Comment by enchorb** [comment]
Using `1.0.3`, `toast.info` and `toast.warning` don't exist. If  you try and call them you get `sonner__WEBPACK_IMPORTED_MODULE_6__.toast.info is not a function`. Even TS complains with `TS2339: Property  info  does not exist on type`

**Comment by emilkowalski** [comment]
Yes, it has not been released yet, i'll do that this week.

**Comment by alieldeba** [comment]
Please release it quickly ❤️
