### ISSUE TITLE
Request: Add Border Sizing and Background Color Changing Features

### ISSUE THREAD

**Issue by codebyaadi** [emilkowalski/sonner#204]
I'd like to propose the addition of two user-interface customization features to enhance the flexibility and visual appeal of the library. These features include the ability to adjust border sizing and change the background color of toasts.

**Comment by basavarajakj** [comment]
If you need this feature let me assign or inform

**Comment by emilkowalski** [comment]
You can do that via the style prop.

**Comment by codebyaadi** [comment]
I tried this 
`<Toaster position="bottom-right" expand className="bg-red-500" />`

and this

`<Toaster position="bottom-right" expand style={{backgroundColor: "#025252", borderRadius: "64px"}} />`

It didn't work
