### ISSUE TITLE
Feature suggestion: autoclose when visible and turn off autoclose

### ISSUE THREAD

**Issue by lucasspra** [emilkowalski/sonner#205]
Hey guys! Your lib is great! 🫶

I'd like to suggest 2 things:
- The possibility of turning off autoclose

- The possibility of starting autoclose countdown only when a snackbar is visible:
  - when it is on the top of the stack
  - or when the container (Toaster) is expanded

Thanks!

**Comment by emilkowalski** [comment]
> The possibility of turning off autoclose

This already exsist and can be added with the dismissible option. See https://sonner.emilkowal.ski/toast for more information.

`The possibility of starting autoclose countdown only when a snackbar is visible`

Do you mean to start a countdown only if a toast is visible = being on top of the stack?

**Comment by emilkowalski** [comment]
> @emilkowalski I've tested the `dismissible` option with `toast`, `toast.success` and `toast.custom` and with every one of them the toast was closed automatically after the default duration 🤔
> 
> Here's what I meant about my second suggestion:
> 
> ![image](https://user-images.githubusercontent.com/70417549/278343105-3c9a3740-5bcf-4a86-96e8-1ece836adf34.png)
> 
> ![image](https://user-images.githubusercontent.com/70417549/278344420-b231b37b-e67c-4c27-8a0c-a8cc3c135175.png)

You probable set it to `true`, it need to be false. As for the other features, I'd like to keep the logic as is for now, but thanks for the suggestions!
