### ISSUE TITLE
Dismiss all not working with headless toasts.

### ISSUE THREAD

**Issue by kubahrom** [emilkowalski/sonner#208]
When I'm using headless toasts created with _toast.custom(...)_ and trying to close all with _toast.dismiss()_ without ID parameter, headless toasts are not closed. Works fine with default ones or if dismissing by ID.

[https://codesandbox.io/s/sonner-headless-toasts-dismiss-rxtdsx](https://codesandbox.io/s/sonner-headless-toasts-dismiss-rxtdsx)

Is there a way to close all toasts including the headless ones?

**Comment by emilkowalski** [comment]
Fixed in #218
