### ISSUE TITLE
add a default `Info` version of the toast

### ISSUE THREAD

**Issue by statusunknown418** [emilkowalski/sonner#209]
similar to other libraries where the `Info` type has a blueish color to it and an InfoIcon

**Comment by bujikun** [comment]
I went through the example on the site and found something about info

`toast.info('Be at the area 10 minutes before the event time')`

But i can not use it in my code, it's as if it's not there. Please restore it.

**Comment by GentikSolm** [comment]
Its in the source code & on the demo website, but its not released yet. @emilkowalski Is there something blocking this? Personally waiting on the warning feature. More than happy to make a PR if work needs done for a npm release.

**Comment by GentikSolm** [comment]
This is now added, Issue can be closed.
