### ISSUE TITLE
Custom Toast With tailwind custom Color hex values is not working

### ISSUE THREAD

**Issue by SahilPanhotra** [emilkowalski/sonner#210]
https://codesandbox.io/s/recursing-farrell-w58cwl?file=/src/App.js

here is a minimal example for what i am trying to do with CustomToast 

Issue:When i am trying to pass color props as hexValues it doesn't work but with prebuilt tailwindClasses it's working also if  i am using style attribute in CustomToast it's working but not with custom hexValues in tailwind .

What am i doing wrong ?also if there is anyother way to pass hover class to certain element of customtoast component.Please let me know Coz in my real project even prebuiltclasses of tailiwind are not working of which i was unable to reproduce the error

**Comment by emilkowalski** [comment]
I'd try posting it as a tailwind issue.

**Comment by JosePadilla98** [comment]
Did tailwind resolve this?
