### ISSUE TITLE
Toast Promise - In the API request created with RTK async thunk, success toast runs even though the HTTP request failed.

### ISSUE THREAD

**Issue by fulutas** [emilkowalski/sonner#215]
I use sonner toast in react projects with great pleasure. But there is a problem with using promises.

The code below runs success toast even though the HTTP request failed.

COMPONENT SUBMIT CODE:
toast.promise(dispatch(AnonymousSaveIssue(postData)).then(res => {
if (res.meta.requestStatus === "fulfilled") {
return navigate(`/issue-result/${res.payload.issueID}?BusinessChannelID=${PAGESTATE.BusinessChannelId}`, { state: { issueId: res.payload.issueID } })
}
}), {
loading: 'Saving notification...',
success: (data) => {
return `Notification created successfully.`;
},
error: 'Error',
});

ASYNCTHUNK in RTK SLICE:
export const AnonymousSaveIssue = createAsyncThunk('AnonymousSaveIssue/POST', async (postData) => {
   return new Promise(async (resolve, reject) => {
     try {
       const response = await [http://request.post](https://t.co/qgRy2igIWg)(`${endpoints.issueEntry.anonymousSaveIssue}?businessChannelId=${PAGESTATE.BusinessChannelId}`, postData);
       if (response.status === 200) {
         resolve([http://response.data](https://t.co/BWRRX5MrEg));
       } else {
         reject({ status: response.status, message: 'HTTP response status is not 200.' });
       }
     } catch (error) {
       console.log(error)
       reject(error);
     }
   });
});

**Comment by emilkowalski** [comment]
Please, provide a codesandbox demo with reproduction.

**Comment by constDEFE** [comment]
Not sure about rtk, but even with the fetch api, it doesn't seem to handle a 404 code as an error
Here's a [sandbox](https://codesandbox.io/p/sandbox/nifty-oskar-4yjdxy?file=%2Fsrc%2FApp.tsx)

**Comment by emilkowalski** [comment]
Fixed in #223
