### ISSUE TITLE
error with toaster component

### ISSUE THREAD

**Issue by reveurguy** [emilkowalski/sonner#22]
Hello
I am using the toaster component and after updating some packages, i am getting error with the Toaster component.

<img width="854" alt="Screenshot 2023-03-04 at 6 21 31 PM" src="https://user-images.githubusercontent.com/59417546/222902411-0de2c8dd-e117-4734-98ce-24b434cc81ae.png">

This is the ss of the errors. When i comment out the Toaster call in main layout, the site is working fine. Because of the error, nothing is visible on the site, just plain white color.

It was working fine till yesterday only, then i updated all the packages using npm-check-update and since then the Toaster is giving errors. I think there is some issue of sonner with the version of other packages.

Any help?

**Comment by emilkowalski** [comment]
I can't reproduce this problem, could you share a https://stackblitz.com/ link that reproduces it?

**Comment by joaom00** [comment]
I get this error in next `app/` dir when use `Toaster` without `use client` directive.

**Comment by emilkowalski** [comment]
Yea, use client is required for it to work.
