### ISSUE TITLE
Feature suggestions: Overwrite explicit the classes of error or success message as default.

### ISSUE THREAD

**Issue by Crinchy** [emilkowalski/sonner#226]
Hey,
You might could add something like errorClasses and successMessage to the <Toaster /> Component, so everyone can set own default styles/classes for error and success messages. Since currently its only possible to give general classNames to the component.

**Comment by nanaaikinson** [comment]
@Crinchy, you can create your own `<Toast />` component and supplier it to the `toast.custom()` function. Below is an example of how I achieved custom styling.

```tsx
// notify.tsx

import Toast from "@/components/ui/toast";
import { toast } from "sonner";

export type ToastVariant = "error" | "danger" | "success" | "warning" | "info" | "default";

export interface INotify {
  message: string;
  title?: string;
  variant?: ToastVariant;
  dismissible?: boolean;
}

export const notify = ({ title, message, variant, dismissible}: INotify) => {
  toast.custom((t) => (
    <Toast
      title={title}
      message={message}
      variant={variant}
      dismissible={dismissible}
    />
  ));
};
```

Instead of calling the `toast()` function provided by sonner, I call my custom `notity()` function. I hope this helps?

**Comment by Crinchy** [comment]
@nanaaikinson, thanks for your suggestions, i thought about the same idea and implemented this util.
```
import { toast } from 'sonner';

export default class Notification {

  static success (message: string) {
    return toast.success(message, {
      className: '!border-2 !border-green-500 !bg-green-600 !hover:border-green-600 !hover:bg-green-700 !text-white !select-none'
    });
  }

  static error (message?: string | null) {
    return toast.error(message || 'Something went wrong!', {
      className: '!border-2 !border-red-500 !bg-red-600 !hover:border-red-600 !hover:bg-red-700 !text-white !select-none',
    });
  }
}
```

**Comment by emilkowalski** [comment]
This is now possible, see https://sonner.emilkowal.ski/styling.

**Comment by Crinchy** [comment]
> This is now possible within Sonner, see https://sonner.emilkowal.ski/styling.

I meant to specify classes for a specific cases, like different classes for success and error toasts. What you changed, is just globally set classes for toasts, but not for specific cases. Check out my code example above.
