### ISSUE TITLE
rendering 2 toasts

### ISSUE THREAD

**Issue by Ozanyurdakul98** [emilkowalski/sonner#235]
had to install 1.2.1 instead of 1.2.2, because a toast always got rendered twice. checked with console.log() if the parent function got called twice, but no, it didnt. Also there is a console.log in index.mjs file which prints undefined unnessesary often.
Not able to provide any reproducable code now, but i like this package a lot. So this are my 2 cents. Thanks for your work.

**Comment by Ozanyurdakul98** [comment]
<img width="795" alt="Bildschirmfoto 2023-11-22 um 23 08 30" src="https://github.com/emilkowalski/sonner/assets/68496958/ada10959-a730-4ffa-83a6-202f0e618d5b">

 Detected the issue.
It doesnt has anything to do with the version. If i put all those buttons as type="submit", the toast gets called 2 or 3 times. depends on the amount of buttons with type submit. Even tho..! the submit handler gets called only one time and the other buttons are obviosly not rendered because of the ternary conditions.
So i will fix this by not using the type="submit" functionality, even it would be better ux

**Comment by Ozanyurdakul98** [comment]
Fixed it to work with type="submit" by using only one button with type submit and handling the function call in the onSubmit callback of the form.

Below an image of the console.logs

![Bildschirmfoto 2023-11-22 um 23 25 48](https://github.com/emilkowalski/sonner/assets/68496958/8a3986af-3579-46a1-9a07-73166ca30187)

**Comment by emilkowalski** [comment]
Please upgrade to the newest version to get rid of the console logs.

**Comment by CodePistol** [comment]
I'm facing this issue as well. Two toasts are getting rendered even when I am calling toast.error only once.

**Comment by emilkowalski** [comment]
did you update the newest version?
