### ISSUE TITLE
Console.log() filling browser console

### ISSUE THREAD

**Issue by tomzvilla** [emilkowalski/sonner#236]
I noticed that you left a console.log in index.tsx and it's triggering my OCD.

Every time you render a toast it will print the prop "classNames" 3 times.

![image](https://github.com/emilkowalski/sonner/assets/89234039/3dd643a0-2a09-4221-a134-42fe4ee19dcf)

**Comment by emilkowalski** [comment]
Pushed a new version!

**Comment by othorizon** [comment]
thanks you two!!! you save me!!!
I am really OCD, and it took me a long time to find out that the logs came from here.
