### ISSUE TITLE
New Suggestions

### ISSUE THREAD

**Issue by Crinchy** [emilkowalski/sonner#237]
## Hey @emilkowalski

some ideas i got today for sonner,

### Following properties ideas for to `<Toaster />` Component:
- Add `closeButtonPosition` (_top left_, _top right_, _bottom left_ and _bottom right_), which allows you to change the position of the close button, as i know the most close buttons are right aligned.
- Add `closeOnClick`, which allows you to close the toast i clicked on, without showing the user any close button or something.

Would be cool, if these suggestions could be implemented ❤.

**Comment by devlopersabbir** [comment]
Thanks for your great idea.. 😊

**Comment by emilkowalski** [comment]
You can change the position of the closeButton via css, see the styling section [here](https://sonner.emilkowal.ski/styling). 

As for the `closeOnClick` functionality, this is not something I'd want to add to the library, but you can do that yourself by adding an onClick event and removing the clicked toast programmatically.
