### ISSUE TITLE
Can I create a vue component for sonner ? 

### ISSUE THREAD

**Issue by cpreston321** [emilkowalski/sonner#24]
Hello! 👋,

I as just wondering if I could create a Vue Component for this, either I can integrate with current repo but downside is It would have to be restructured for Vue and React components but also setting up a monorepo. Either way just let me know thanks.

Once it's in Vue it then can compiled down into a `Custom Element` which would be framework agnostic.

Thanks! 
CP

PS. Thanks for creating this amazing toast!

**Comment by yuyinws** [comment]
Looking forward to the Vue Component!

**Comment by emilkowalski** [comment]
Let's not integrate with current repo, feel free to port it tho!
