### ISSUE TITLE
Styling of loader/promise toast

### ISSUE THREAD

**Issue by Rjuks** [emilkowalski/sonner#244]
Hello, 

I'm trying to customize Toast colors, but also i want to use promise/loading toast. 

```
          toastOptions={{
            classNames: {
              error: "bg-red-400",
              success: "text-green-400",
              warning: "text-yellow-400",
              info: "bg-blue-400",
              loader: "bg-blue-400",
            },
          }}
```

But styles for "loader" are not working, even if I apply `unstyled: true` then promise/loading toast ends with reset styling.

**Comment by Rjuks** [comment]
> So you'd basically want a `promise` key?

I would like to customize loader and promise toast styles in `toastOptions`.

**Comment by angelocala94** [comment]
@Rjuks use `loading` instead of `loader`. (#255)

**Comment by emilkowalski** [comment]
Like @angelocala94 mentioned!

**Comment by chukwudobemicah** [comment]
tried loader & loading, none worked
