### ISSUE TITLE
add styles.css to /dist

### ISSUE THREAD

**Issue by FrancoJavierGadea** [emilkowalski/sonner#246]
While working with Astro and View transitions, I noticed that the <style></style> tag injected into the head with CSS styles does not persist when navigating between pages. This occurs because the script executes only once at the beginning.

This can be addressed by directly importing the CSS styles, but since they are not included in the final bundle, they need to be downloaded from GitHub.

Please consider adding the CSS styles to the final /dist bundle.

**Comment by FrancoJavierGadea** [comment]
https://stackblitz.com/edit/github-pvwvns

**Comment by joelmoss** [comment]
I'm coming across this issue also. Would be great if we culd have control over loading styles, or as @FrancoJavierGadea has requested, to include the styles in `/dist`. thx

**Comment by sidneifjr** [comment]
Same here. I attempted to follow the Tailwind's style guide as shown in the docs (https://sonner.emilkowal.ski/styling#tailwind-css), but alas, no success.

**Comment by broisnischal** [comment]
Hey i am facing same sort of issue when working with REMIX application!

**Comment by HaiveDev** [comment]
The solution that worked for me was to directly embed the styles in the layout. You can find the styles at the following link:
 [https://github.com/emilkowalski/sonner/blob/main/src/styles.css](https://github.com/emilkowalski/sonner/blob/main/src/styles.css)

**Comment by canadianeagle** [comment]
> The solution that worked for me was to directly embed the styles in the layout. You can find the styles at the following link: https://github.com/emilkowalski/sonner/blob/main/src/styles.css

Thank you - this fixed my issue in Remix. 🙏🏾

**Comment by broisnischal** [comment]
:heart:

**Comment by emilkowalski** [comment]
Let's use the solution @HaiveDev suggested.

**Comment by bkilrain** [comment]
Sorry - @HaiveDev and others. What do you mean by "embedding the styles directly in the layout?" Do you mean to copy them from github and paste them into your app? 

@emilkowalski - would you accept a PR to add the stylesheet to /dist as @FrancoJavierGadea originally suggested?

**Comment by DiederikvandenB** [comment]
This is a terrible solution. What do we do when the package is upgraded and styles are changed?
