### ISSUE TITLE
index page button style bug on dark mode

### ISSUE THREAD

**Issue by muvich3n** [emilkowalski/sonner#251]
https://github.com/emilkowalski/sonner/assets/75461217/f23dd02c-2f61-4425-827a-d7939103d590

This seems like a style bug.
I can help but I'm not sure what kind of style you wanna achieve, so i just report the bug here :)

**Comment by emilkowalski** [comment]
This page is meant to be viewed in light mode only, I'll force that, tanks for reporting!

**Comment by muvich3n** [comment]
> This page is meant to be viewed in light mode only, I'll force that, tanks for reporting! 

You're welcome! Thanks for your building this wonderful component :)
