### ISSUE TITLE
Positioning variable depending on breakpoint

### ISSUE THREAD

**Issue by DoctorSte** [emilkowalski/sonner#253]
I want to set up my toast as 'top-right' on lg+ resolutions and 'bottom-centre' on all others. 
Is there a way to do that through the Toaster options?

**Comment by yasseralsaidi** [comment]
me too i need this?

**Comment by devlopersabbir** [comment]
these options have or not??

**Comment by DoctorSte** [comment]
Not yet as far as I can tell. Even if positioning can be disabled so I can position it myself with Tailwind classes that would work. But of course a way to do that through props would be preferred.

**Comment by aXenDeveloper** [comment]
You have `window.innerWidth` to detect width of your screen.

```tsx
<Toaster position={window.innerWidth >= 1500 ? "top-center" : "top-left"} />
```

**Comment by emilkowalski** [comment]
Let's use @aXenDeveloper for now.
