### ISSUE TITLE
RTL Direction shows incorrect Position

### ISSUE THREAD

**Issue by yasseralsaidi** [emilkowalski/sonner#254]
I am facing an issue with the direction (RTL).
when I set the layout to dir='ltr,' the position appears normal.
However, when I set dir='rtl,' the position is incorrect.

update: i found the problem with data-x-position and for temporarily soultion i change the postion to "bottom-center" but i want a default value whcih is bottom-right for larg device and bottom-center for small device
any fix?

See the attachemnt pic below...

ltr
![screenshot-localhost_3000-2023 12 13-16_32_4102](https://github.com/emilkowalski/sonner/assets/70948326/f23146a6-e499-4ad8-b742-aebc9e6ebb2b)

rtl
![screenshot-localhost_3000-2023 12 13-16_30_5201](https://github.com/emilkowalski/sonner/assets/70948326/35677d8c-070b-469e-ac4f-a9761bb42c86)

**Comment by emilkowalski** [comment]
rtl = right to left, so I think it's working correctly in the second image?
