### ISSUE TITLE
TypeScript Error with loading Class in toastOptions and UX Suggestion for Loading Toast

### ISSUE THREAD

**Issue by angelocala94** [emilkowalski/sonner#255]
I've encountered a couple of issues with the Sonner component that I'd like to bring to your attention:

1. TypeScript Error with loading Property: Using the className loading in toastOptions correctly applies the style, but TypeScript shows an error. This seems to be a mismatch in TypeScript definitions.
https://github.com/emilkowalski/sonner/blob/7560716b5ab9644b6695a0fcd1b6363b2eda6f81/src/types.ts#L18

   ```jsx
   <Sonner
      toastOptions={{
        // ... other options ...
        classNames: {
          // ... other class names ...
          loading:  'class-1 class-2',
        },
      }}
      // ... other props ...
    />
   ```

3. **UX Suggestion for Loading Toast**: Currently, the toast of type `loading` behaves like other toast types in terms of auto-dismissal. For a better user experience, I suggest that the `loading` toast should not auto-dismiss like the others. Instead, it would be more practical for it to remain visible indefinitely until manually dismissed using its ID.

**Comment by emilkowalski** [comment]
Great suggestions, added in #298
