### ISSUE TITLE
The Close Button example from the Other section toggles the `closeButton` state

### ISSUE THREAD

**Issue by ubmit** [emilkowalski/sonner#256]
The "Close Button" example in the "Other" section at https://sonner.emilkowal.ski/ is causing confusion for new users. Clicking the button toggles the ﻿`closeButton` state instead of setting it to true. 

https://github.com/emilkowalski/sonner/blob/7560716b5ab9644b6695a0fcd1b6363b2eda6f81/website/src/components/Other/Other.tsx#L57

This means that after the first click, a toast with a close button appears as expected. However, clicking the button again creates a new toast without a close button. I couldn't find a good solution for this issue. Initially, I considered always setting ﻿`closeButton` to true, but that would affect all existing and future toasts. I also tried setting it to false in both the `﻿onDismiss` and ﻿`onAutoClose` callbacks, but that created side effects as well.

**Comment by emilkowalski** [comment]
This is by design, thank you for the suggestion tho!
