### ISSUE TITLE
Custom toast with anchor tags not working on firefox

### ISSUE THREAD

**Issue by glpecile** [emilkowalski/sonner#258]
While trying to write a [custom toast](https://sonner.emilkowal.ski/toast#custom) with an anchor tag added like the following example code:
```jsx
toast.info(
<span> 
	text{" "}
	<a target={"_blank"} rel={"noreferrer"} href={url}>
		link
	</a>{" "}
	more text.
</span>
);
```
it works flawlessly as intended in chromium browsers but in firefox links don't seem to open at all.
Any help?

**Comment by jschoder** [comment]
I can reproduce it and are currently looking for a possible solution.
