### ISSUE TITLE
Theme toggle button style bug

### ISSUE THREAD

**Issue by RockingThor** [emilkowalski/sonner#260]
<img width="325" alt="Screenshot 2023-12-19 at 7 53 12 PM" src="https://github.com/emilkowalski/sonner/assets/121621183/42bcb2e4-66de-410e-9ff2-5f3e24c0a6b2">

The tick icon is overlapping and the left padding is missing.

**Comment by aXenDeveloper** [comment]
<img width="269" alt="image" src="https://github.com/emilkowalski/sonner/assets/58148176/0944ae12-3da7-4a73-bee9-c1fafd7e8982">

More info please.

**Comment by emilkowalski** [comment]
Please post it in the [Nextra](https://github.com/shuding/nextra) project as the styles are coming from there.
