### ISSUE TITLE
Compatibility with Deno / Fresh

### ISSUE THREAD

**Issue by hapaxlife** [emilkowalski/sonner#262]
Hi,

When Fresh checks code before running, `document` is not defined at line 402 https://github.com/emilkowalski/sonner/blob/main/src/index.tsx#L402. At this moment, Fresh has no context so `document` doesn't exists.

When Fresh runs code, `document` exists.

To make it works, is it possible to add a check on document just after line 400 https://github.com/emilkowalski/sonner/blob/main/src/index.tsx#L400

Before
```ts
function getDocumentDirection(): ToasterProps['dir'] {
  if (typeof window === 'undefined') return 'ltr';

  const dirAttribute = document.documentElement.getAttribute('dir');
 ```
 
 After
 ```ts
 function getDocumentDirection(): ToasterProps['dir'] {
  if (typeof window === 'undefined') return 'ltr';
  if (typeof document === 'undefined') return 'ltr';  // For Fresh purpose

  const dirAttribute = document.documentElement.getAttribute('dir'); 
  ```

I made a pull request

**Comment by emilkowalski** [comment]
Thank you, merged!
