### ISSUE TITLE
Whilst using ShadCn UI' Sonner, you get an error in deployment

### ISSUE THREAD

**Issue by Condrey** [emilkowalski/sonner#265]
When deploying to Vercel, you might come across this error
`Syntax error: /vercel/path0/src/app/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive. (1:1)`

the error comes from the 
src/components/ui/sonner.ts file
```TYpeScript
<Sonner
...
classNames:{
 toast: "group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground group-[.toaster]:border-border group-[.toaster]:shadow-lg",
...
},
...
/>
```

**Comment by qoobes** [comment]
Can add your css file(s) and more importantly your tailwind configuration to the issue as well?

**Comment by emilkowalski** [comment]
Like @qoobes mentioned, preferably a codesandbox with reproduction.

**Comment by Mespeet** [comment]
A bit late to the party, and it is also completed, but changing the `border-border` to `border` fixed it for me 😄
