### ISSUE TITLE
Custom `loadingIcon` inherits `toast` classes even though it is rendered inside one

### ISSUE THREAD

**Issue by samlaycock** [emilkowalski/sonner#267]
Looking at the code, I'm not sure if this is intentional or not..?:

https://github.com/emilkowalski/sonner/blob/9b0dcae72def5fb8af048b8dfdf9dbfd0a1c6b44/src/index.tsx#L200

It means that the custom `loadingIcon` is rendered with the toast's classes, which causes a double rendering of styles (background, shadows etc.). I think it would be better if the `loadingIcon` prop was completely agnostic to any other external styles, as you've already opted into rendering the loading component yourself entirely anyway?

Example:

<img width="383" alt="Screenshot 2023-12-25 at 10 18 33" src="https://github.com/emilkowalski/sonner/assets/93922969/047549e5-b235-4dcb-bd02-850724399e09">

**Comment by emilkowalski** [comment]
Good catch, fixed in #268
