### ISSUE TITLE
Rapidly creating new toasts causes strange rendering behavior

### ISSUE THREAD

**Issue by pckilgore** [emilkowalski/sonner#27]
Reproduction: https://codesandbox.io/s/wonderful-brook-9wrw4c?file=/src/App.tsx

Loom of what I see: https://www.loom.com/share/45ce40b6c6294585b503ef1d00725bca

The repro is obviously a worst-case, but we observe the behavior in file-uploading code that concurrently uploads 5 files at a time from a batch uploader and streams back processing results.  It creates toasts far less rapidly, but still suffers from this issue.

Otherwise, cool library!

**Comment by emilkowalski** [comment]
This has been fixed in v0.2.0, https://codesandbox.io/s/epic-goldwasser-z7qujx?file=/src/index.tsx.
