### ISSUE TITLE
How to get a handle to internal mounted state for checking if it first render or not?

### ISSUE THREAD

**Issue by ahmetkca** [emilkowalski/sonner#272]
is there a way to get the internal `mounted` state to check if it is first render or not? From what I understand sonner already renders your custom component ones for triggering css animations.

```js
React.useEffect(() => {
    // Trigger enter animation without using CSS animation
    setMounted(true);
}, []);
```

https://github.com/emilkowalski/sonner/blob/c449e2741368b04b4524859aa2a60696c0cfb58c/src/index.tsx#L105C26-L105C26

**Comment by emilkowalski** [comment]
What's your use case?

**Comment by ahmetkca** [comment]
I had a toast. Promise toast where I show progress of the uploads of the files. I was passing promises and doing some state update whenever a promise is resolved. I was updating the states twice the size of promise list somehow and I thought this was the problem. Fortunately, I resolved by creating my own first render check with useRef.
