### ISSUE TITLE
Unable to interact with Toast when Sheet is open.

### ISSUE THREAD

**Issue by envyvox** [emilkowalski/sonner#275]
Hey there, I am using [chadcn](https://ui.shadcn.com/) components and wanted to replace old toast component with sonner.
But I've run into a problem that I can't interact with sonner toast's while Sheet/Modal on screen.

https://github.com/emilkowalski/sonner/assets/6567597/c0627da8-ccc8-41c5-af5a-1add6d0ad27d

Any tips on how to fix this?

**Comment by envyvox** [comment]
Probably the problem isn't z-index at all, so I'm hoping someone will explain how to fix it.

**Comment by emilkowalski** [comment]
In your case you can use `modal={false}` on `Drawer.Root`

**Comment by metuan** [comment]
@emilkowalski In that case, it will close the panel when you e.g. close the toast or when you want to copy a text that inside of it. Is there an option to keep the panel open while allowing interactivity with the notif?
