### ISSUE TITLE
duration: Infinity silently breaks toasts

### ISSUE THREAD

**Issue by jacob-orbiit** [emilkowalski/sonner#287]
### Describe the feature / bug 📝:

When `duration` is set to `Infinity` as recommended in https://github.com/emilkowalski/sonner/issues/190, the toast never shows (it appears to never get added to the DOM).

### Steps to reproduce the bug 🔁:

1. Set `duration` via
   * `<Toast duration={Infinity} />`
   * `<Toast toastOptions={{ duration: Infinity }} />`
   * `toast('hej', { duration: Infinity })`
2. Trigger the toast
3. Observe no toast

react@18.2.0¹
sonner@1.3.1¹

¹ latest at time of this post

Otherwise, sonner is pretty sweet! (love that it doesn't use a hook, so it can be triggered outside a component)

**Comment by sirtobey** [comment]
Second this, `Number.MAX_SAFE_INTEGER` also does not display the toast.

**Comment by emilkowalski** [comment]
`toast('hej', { duration: Infinity })`

This renders the toast for me that stays on the screen without any issues, am I missing something?

**Comment by jacob-orbiit** [comment]
> am I missing something?

Apparently, the part where it doesn't work at all. No idea why it's working for you. For me, `duration: Infinity` functions exactly like an off switch.

**Comment by emilkowalski** [comment]
Can you create a codesandbox with reproduction?
