### ISSUE TITLE
Sonner is hidden behind keyboard on mobile

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [emilkowalski/sonner#289]
### Describe the feature / bug 📝:

If you have the keyboard on mobile open and then the toast is triggered the toast is hidden behind the keyboard

### Steps to reproduce the bug 🔁:

1. Create a toast event while being e.g. in an input

### Possible solutions

Check if the keyboard is open and if it has a small aspect ration (and maybe if it's on mobile or has a digital keyboard). And then move the toast to the top.

**Comment by emilkowalski** [comment]
I'd suggest changing the position in your app to render the toast on top rather than bottom when the keyboard is open. Building it into Sonner is not worth the performance trade-off.
