### ISSUE TITLE
It breaks my package.lock

### ISSUE THREAD

**Issue by ilearnio** [emilkowalski/sonner#290]
### Describe the feature / bug 📝:

I have a monorepo project with npm workspaces, when installing sonner, it changes my package.lock by removing my `frontend/node_modules/react` package and reinstalling react from "node_modules/react". Same version but it breaks my app. If you could remove "peerDependencies" from your package.json, I would really appreciate it! IMO it only adds errors most of the times and provides no benefits

![image](https://github.com/emilkowalski/sonner/assets/14331216/7acc7bfb-64f3-4845-9bc2-b24d400bea58)

**Comment by Rychillie** [comment]
try deleting `node_modules` and `package.lock` and reinstalling all packages

**Comment by emilkowalski** [comment]
Like @Rychillie mentioned, did that help?

**Comment by ilearnio** [comment]
@emilkowalski I tried but that didn’t help. So what I did is I temporarily fixed the package.lock manually, and reinstalled everything with “npm ci”
