### ISSUE TITLE
`closeButton` doesn't work on individual toasts via `toastOptions`

### ISSUE THREAD

**Issue by MarkLyck** [emilkowalski/sonner#292]
### Describe the feature / bug 📝:

The documentation shows `closeButton` as an option under `API Reference` for toast() and says it's default value is `false`

https://sonner.emilkowal.ski/toast#api-reference

However if I try to add `closeButton` in the toast options, I get a TypeScript error saying it's not an available option, and when the toasts show up there's no close button.

the `closeButton` does show up when I make it a prop on the `Toaster`. But  I don't want all of my toasts to have it, only my error toasts, or some specific toasts with long messages.

### Steps to reproduce the bug 🔁:

```
toast.error('example that does not work', { closeButton: true  })
```

**Comment by emilkowalski** [comment]
This has been fixed in #296, thank you for reporting.
