### ISSUE TITLE
Website Application Errors - Clicking many of the examples crashes page

### ISSUE THREAD

**Issue by nkeat12** [emilkowalski/sonner#293]
### Describe the feature / bug 📝:

Application errors on many of the examples on https://sonner.emilkowal.ski/ 

### Steps to reproduce the bug 🔁:

1. Go to https://sonner.emilkowal.ski/
2. Click on "Error" under types (there are many more that crash the page this is one example).

https://github.com/emilkowalski/sonner/assets/8729807/f7f4ea98-79be-4e3d-90f4-7803d04c438b

**Comment by gitatractivo** [comment]
Hi there! I'm really enjoying the experience with 'sonner' in my React project. I also saw this issue can I help fix this issue?

**Comment by emilkowalski** [comment]
Thank you, this has been fixed now!
