### ISSUE TITLE
Conditionally open/close toast

### ISSUE THREAD

**Issue by sajadevo** [emilkowalski/sonner#3]
Hey,

Thanks for creating such a great tool, it's really awesome.
I want to know is there is any specific way for conditionally opening and closing the toast?

**Comment by skoshx** [comment]
Just chiming in here, but it might be useful to show some examples of what you mean by "conditionally opening and closing the toast". To me, it sounds like you can solve this by just using some basic if-statements?

**Comment by emilkowalski** [comment]
So you'd want to open and close the toast programatically, is that right?

**Comment by sajadevo** [comment]
> Owner

Yes it's the way that I want to do it.

**Comment by tnmyk** [comment]
@emilkowalski I was playing around and was able to somewhat achieve this, but only when there is only one subscriber i.e `(toast) => {setToasts((toasts) => [toast, ...toasts]);}`
    
Can you explain why we have array of subscribers? 😅

**Comment by emilkowalski** [comment]
This has been added in #18! 🎆
