### ISSUE TITLE
CSS class "loader" overlaps 

### ISSUE THREAD

**Issue by coder-Rit** [emilkowalski/sonner#305]
### Describe the feature / bug 📝:
Sonner's CSS class "loader" overlaps with the user's custom CSS className "loader".
N/A

### Steps to reproduce the bug 🔁:

1. Create a span element that has the className "loader".
2. Add Sonner code in that JSX element.
3. observer the behavior of the span element's "loader" class.

adds the property "display: absolute" 
![Screenshot (1069)](https://github.com/emilkowalski/sonner/assets/83896563/2ae67ce9-8c7a-4027-817f-007ed6ef4d28)

 change the name of class to "loaderPersonal"->works fine
 
![Screenshot (1070)](https://github.com/emilkowalski/sonner/assets/83896563/452c0bdd-853f-4bd1-884a-66cb2a74e060)

**Comment by jschoder** [comment]
@coder-Rit The fix in the code was pretty straight forward. It was using the general `.loader`className which will break other code using the same className. I don't see a way to fix this outside the project and the only workaround is not to use the general `.loader`class, which probably a good strategy anyway.
