### ISSUE TITLE
Animations broken???

### ISSUE THREAD

**Issue by sujjeee** [emilkowalski/sonner#316]
https://github.com/emilkowalski/sonner/assets/101963203/023c55a0-3d79-42e9-bb2c-67fa35f58842

**Comment by datner** [comment]
you probably have some 'prefer-reduced-motion' like if you set no animations on mac

**Comment by wobsoriano** [comment]
https://github.com/emilkowalski/sonner/issues/96

**Comment by sujjeee** [comment]
@datner what about windows/chrome??

**Comment by datner** [comment]
@sujjeee all operating systems have these settings OS-wide which affect the browser, and also browsers have these settings for themselves which affect all websites. I would know, I have these one 😄 

I don't have motion sickness or something, I'm just very impatient lol
