### ISSUE TITLE
`unstyled: true` has stopped working?

### ISSUE THREAD

**Issue by tcolinpa** [emilkowalski/sonner#323]
I'm on v1.4.0 and finding it hard to style child elements even with `unstyled: true` on `toastOptions`.

Seems like a bunch of css selectors as `[data-sonner-toast]` stills exists and with specificity (0, 1, 0) -- sometimes higher when combining selectors such as `[data-sonner-toast] [data-cancel]`

**Comment by emilkowalski** [comment]
I'm able to style the elements just fine with the unstyled prop. Please provide a CodeSandbox demo with reproduction.

**Comment by tcolinpa** [comment]
Hi @emilkowalski!

Just forked shadcn-ui-vite and put sonner there. Here's a demo https://codesandbox.io/p/live/b84f7a71-3892-476c-af18-0c349485b48a.

If you inspect the toast shown, it will pop-up some css that I've had a hard time overwriting with higher specificity. Sure, it can be solved by a bunch of !important, but it kind of gave me a inconsistent results (this might be a skill problem though 😅).

Maybe related to #321 and #248?

**Comment by tcolinpa** [comment]
Nvm

Just read #216 and did as you said
```css
style={{
        fontFamily: "inherit",
      }}
```
