### ISSUE TITLE
Toast not working

### ISSUE THREAD

**Issue by vinnycosta9898** [emilkowalski/sonner#326]
I'm using version 1.4.0 ans toast isn't work

What am I doing

1.  Install sonner 
2. Add  library in the source project
3. Trying display toast

**Comment by maariyadiminsky** [comment]
I'm having the same issue.

**Comment by emilkowalski** [comment]
Ensure you add `<Toaster />` https://sonner.emilkowal.ski/getting-started#add-toaster-to-your-app
