### ISSUE TITLE
Toast remain open indefinitely until the user closes it

### ISSUE THREAD

**Issue by codeBelt** [emilkowalski/sonner#327]
### Describe the feature / bug 📝:

I couldn't find it in the documentation, but is there a way to keep the toast visible indefinitely until the user decides to close it? Perhaps setting the `duration` to `null` or introducing a `sticky` property could provide this functionality to developers.

We have this toast that we want the user to click on and not have it go away:

<img width="540" alt="Screenshot 2024-02-05 at 5 00 38 PM" src="https://github.com/emilkowalski/sonner/assets/2893563/a1281e56-1e5f-458e-a594-de342078f0a6">

**Comment by binkydog** [comment]
Looks like Emil went with `duration: Infinity` to prevent auto closing.

https://github.com/emilkowalski/sonner/pull/46

**Comment by topaxi** [comment]
Infinity is a bit unfortunate, as JSON does not include it and we triggering/controlling some toasts from certain server responses :sweat_smile:
