### ISSUE TITLE
Bad backdrop filter

### ISSUE THREAD

**Issue by Wollace-Buarque** [emilkowalski/sonner#329]
### Describe the feature / bug 📝:

As you can see only the middle toast is blurred because I put a tailwind class to try remove the blur:
![image](https://github.com/emilkowalski/sonner/assets/29075798/e080465a-f267-43fb-a075-90cb606328e4)

![image](https://github.com/emilkowalski/sonner/assets/29075798/c7a0530a-de49-4304-a2e4-0928a8372fba)

If I don't have that tailwind class:

![image](https://github.com/emilkowalski/sonner/assets/29075798/4d5b81bc-d12c-492f-8634-510c331a590a)

Now only the middle one isn't blurred, and what I want it's that every toast be legible without blur effect.

### Steps to reproduce the bug 🔁:

Just run a toast.

**Comment by lucas-ellwanger** [comment]
I have the same issue here, currently on W11 23H2 and Chrome 121.0.6167.161.

**Comment by devmanbr** [comment]
up

**Comment by emilkowalski** [comment]
I don't follow, are the toasts blurry for you? There is no css added from sonner that might cause it. Which OS and browser are you using?

**Comment by devmanbr** [comment]
> I don't follow, are the toasts blurry for you? There is no css added from sonner that might cause it. Which OS and browser are you using?

Check #334.

**Comment by Wollace-Buarque** [comment]
> I don't follow, are the toasts blurry for you? There is no css added from sonner that might cause it. Which OS and browser are you using?

I'm using Edge and Chrome on Windows 11.

I know this problem and it's because the transform property, take a look at this:

https://stackoverflow.com/questions/14677490/blurry-text-after-using-css-transform-scale-in-chrome
https://stackoverflow.com/questions/36787529/how-to-fix-blurry-image-on-transform-scale
https://stackoverflow.com/questions/31109299/css-transform-translate-50-50-makes-texts-blurry

**Comment by emilkowalski** [comment]
Is this fixed in this preview link? https://sonner-git-fix-blurry-appearance-emilkowalski-s-team.vercel.app/

**Comment by Wollace-Buarque** [comment]
> Is this fixed in this preview link? https://sonner-git-fix-blurry-appearance-emilkowalski-s-team.vercel.app/

![image](https://github.com/emilkowalski/sonner/assets/29075798/e0468d51-37c0-4c34-881a-c16ad0c9dbaf)

I found another fix, setting the `toastOptions={{ style: { willChange: 'unset' } }}` fixed all blurs effect

**Comment by emilkowalski** [comment]
Can you try now? @Wollace-Buarque 
https://sonner-git-fix-blurry-appearance-emilkowalski-s-team.vercel.app/

**Comment by Wollace-Buarque** [comment]
> Can you try now? @Wollace-Buarque https://sonner-git-fix-blurry-appearance-emilkowalski-s-team.vercel.app/

It's fixed now

![image](https://github.com/emilkowalski/sonner/assets/29075798/a8bd4da0-5a20-415a-aca7-18d5576da66c)

**Comment by emilkowalski** [comment]
Fixed in #336
