### ISSUE TITLE
Toasts dismiss at the same time when hovered

### ISSUE THREAD

**Issue by walmartwarlord** [emilkowalski/sonner#332]
### Describe the feature / bug 📝:

When opening multiple toasts and hovering over them, they close at the same time on mouse out:

### Steps to reproduce the bug 🔁:

1. Go to the playground and render toast 3 times (add a bit of delay to each)
2. Hover on the toast and unhover
3. See them close at the same time

https://github.com/emilkowalski/sonner/assets/72330740/bbc76d96-278d-4b3c-9363-91c48ca7ef52

**Comment by revogabe** [comment]
this is the normal operation of `expand={false}` if you want them not to close in a static way you can use `expand={true}`
