### ISSUE TITLE
Toast not displaying when toastOptions.duration (and duration) on Toaster set to Infinity

### ISSUE THREAD

**Issue by deadlinecode** [emilkowalski/sonner#340]
### Describe the feature / bug 📝:

It looks like if i try to set the duration (or toastOptions.duration) on the Toaster element to Infinity so the toast doesn't dissapear the Toast won't show up at all.

### Steps to reproduce the bug 🔁:

I encountered this bug in a project with shadcn while using toast.error (just meant as a info - i don't know how much this affects the outcome).

1. Implement the Toaster component with `duration={Infinity}` or `toastOptions={{ duration: Infinity }}`
2. Try to display a toast and see that it does not display

**Comment by atsixian** [comment]
I had the same problem. After digging into it, I realized it was `setTimeout(, Infinity)` behaves as if the delay is `0`. The toast was actually rendered, but it was closed immediately, so we don't see it.
I created a PR to fix it. cc @emilkowalski 👀

https://github.com/emilkowalski/sonner/blob/94cb71eb0056c743ce76dbcfd16a0ca2d5a0d1da/src/index.tsx#L170-L178
