### ISSUE TITLE
Toast not rendering on page load

### ISSUE THREAD

**Issue by luis-viegas** [emilkowalski/sonner#341]
### Describe the feature / bug 📝:

In Nextjs, when I try to render a toast on page load (inside a useEffect()) nothing happens if the `<Toaster />` is inside layout.tsx, if it is inside the page that is trying to render the toaster everything works fine.

I've putting `<Toaster />` inside a Client component and then inserting it into layout.tsx and it still did not work so that does not seem to be the problem.

### Steps to reproduce the bug 🔁:

I created a stackblitz that makes it easier to reproduce the bug: https://stackblitz.com/edit/stackblitz-starters-hzwlsc?file=app%2Ftest%2Fpage.tsx

However, these are the instructions:

1.Create Next App,
2.Install tailwind,
3.Install Sonner
4. 
```
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}

```

```
'use client';
import { toast, Toaster } from 'sonner';
import { useEffect } from 'react';
export default function Home() {
  useEffect(() => {
    toast('hello');
  });

  return (
    <div>
      <a href="/">
        <h2 className="mb-3 text-2xl font-semibold hover:underline">home</h2>
      </a>
    </div>
  );
}

```

**Comment by luis-viegas** [comment]
Just a quick update/tip, apparently using setTimeout fixes it but I don't know why.
```
setTimeout(() => {
      toast('hello');
    })
```

**Comment by emilkowalski** [comment]
If you want to load it on the initial load a `setTimeout` or `requestAnimationFrame` is required.
