### ISSUE TITLE
`<Toaster />` does not support `icons` on 1.4.0

### ISSUE THREAD

**Issue by greyovo** [emilkowalski/sonner#343]
### Describe the feature / bug 📝:

I found the `icons` attribute on the `<Toaster />` component in the documentation, but it doesn't seem to be available in v1.4.0. 

I checked the commit logs and discovered that the `icons` attribute was exposed on the component after the release of v1.4.0. However, it's confusing that the documentation already mentions it.

**Comment by LucasSouza17** [comment]
I have the same problem

**Comment by GuilhermeLLS** [comment]
Seems like the code is already merged on main, but there was not a package release since then. 

I think it should be available in the next release of the package.

**Comment by zwenza** [comment]
Also have the same problem, `icons` attribute is not available on `<Toaster />` in 1.4.0

**Comment by emilkowalski** [comment]
Released a new version that supports it, sorry about the confusion! https://github.com/emilkowalski/sonner/releases/tag/v1.4.1
