### ISSUE TITLE
Dismissed toasts not removed correctly

### ISSUE THREAD

**Issue by zunkelty** [emilkowalski/sonner#353]
### Describe the feature / bug 📝:

On version 1.4.1 dismissed toasts are not removed correctly. Once dismissed the `<li>` items move to the edge of the page and become invisible but are not removed from the DOM. Other toasts are not updated as well once a toast is dismissed.

This behaviour only occurs on 1.4.1, downgrading to 1.4.0 solved the issue.

### Steps to reproduce the bug 🔁:

1. Use Sonner 1.4.1 in a project and choose `position: bottom-center` (other positions not tested)
2. Display two toasts, set the first toast's duration to e.g. 10000ms and the second one to e.g. 2000
3. When the second toast disappears, the first toast does not expand and stays hidden.

**Comment by lucasdemoraesc** [comment]
Same problem here with the prop ```position``` set to ```"top-center"```

**Comment by zbeyens** [comment]
Same here, the invisible toast is blocking interactivity with buttons placed behind.

**Comment by houmark** [comment]
Same here, I'm using position "top-right" and the entire `section → ol → li` sticks around blocking other UI elements behind. 

Downgrading to `1.4.0` also fixed it for me.

**Comment by houmark** [comment]
Magically, on my end, [v1.4.2](https://www.npmjs.com/package/sonner) was released early monday with no evidence in Github for me (no release, no tag, no recent commits related to this; read witchcraft), but that version fixes the issue for me. Check if you have v.1.4.2 because if you don't, then I'm on a multi-day dream.

**Comment by brandanking-decently** [comment]
Yeah upgrading seemed to work for me too

**Comment by emilkowalski** [comment]
Just released a new version, this should be fixed.

**Comment by Saf3ty1nnumb3rs** [comment]
Can confirm. Upgraded from `1.4.1` to `1.4.3` and the UI blocking issue is resolved. Thank you @emilkowalski
