### ISSUE TITLE
Sugestion - Confirm Toast

### ISSUE THREAD

**Issue by scalarerp** [emilkowalski/sonner#358]
Have a way do use sonner  as a confirmation dialog?

**Comment by emilkowalski** [comment]
I'm not following, isn't that what a toast with action is?

**Comment by adamzerner** [comment]
I think OP is asking about whether sonner can be made to work in a way that is similar to how [`window.confirm`](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) works. Namely, where `toast` would return a boolean indicating whether or not the user hit "Ok" or not. That way you could write code like this:
```
const shouldDelete = toast(...);
```
