### ISSUE TITLE
Red background while hovering toasts

### ISSUE THREAD

**Issue by lirbre** [emilkowalski/sonner#36]
Hey! I was curious about the test implementation and I saw this: 

![image](https://user-images.githubusercontent.com/86065449/224521715-3ea83287-b015-40fc-877f-36e3d44fe087.png)

Tbh I don't think it's intentional so I'm just dropping it here to highlight it.

Also, no hard feelings about closing the PR without the PR, don't worry bud. :)

**Comment by emilkowalski** [comment]
Fixed, thank you!
