### ISSUE TITLE
Idea : Make it for other framework also like Angular or Vue 

### ISSUE THREAD

**Issue by shivamrathore0897** [emilkowalski/sonner#367]
### Feature📝:

I am learning the React and I'll definitely try this one but right now I am working as an Angular Developer and I want to use this in my personal project.
So can you please create one for the Angular also?

**Comment by emilkowalski** [comment]
There is a port for Vue (https://vue-sonner.vercel.app/). Feel free to try and port it out to Anuglar as well! I don't know Angular unfortunately.
