### ISSUE TITLE
Using a React element for `description` displays `[object Object]`

### ISSUE THREAD

**Issue by michaelhays** [emilkowalski/sonner#378]
When I use a React element for `description`, the description displays as `[object Object]`:

```tsx
toast.success("message", { description: <p>description</p> });
```

Reproduction: https://codesandbox.io/p/sandbox/sonner-description-dj3h6f?file=%2Fsrc%2Findex.tsx

This is broken in versions 1.4.31 and 1.4.32, but works as expected in 1.4.3.

**Comment by borisadamyan** [comment]
please try to stringify the value.

toast.success("message", { description: "<p>description</p>" });

description and title it needs to be a string and it can contain HTML Elements

**Comment by emilkowalski** [comment]
@borisadamyan Any chance you could add that to the docs so that more users are aware?

**Comment by borisadamyan** [comment]
@emilkowalski  100%. 
I'll provide a new improvement to make both cases workable

**Comment by borisadamyan** [comment]
in this case, users will be able to use both options in the description.
PR  - https://github.com/emilkowalski/sonner/pull/380

**Comment by 202104104021** [comment]
Same issue here

**Comment by peetzweg** [comment]
Whoops implemented this quickly as well. However, I also added some tests to prevent this happening again in the future. Maybe worthwhile bringing them in as well? #387

**Comment by michaelhays** [comment]
Would love a new release with this fix if possible! :pray:

**Comment by michaelhays** [comment]
@emilkowalski Hate to tag open source maintainers, but thought maybe you missed this -- any chance you could provide a release with the fix for the issue here? I've been pinned to v1.4.3 for a couple of months now.

**Comment by jose-donato** [comment]
> @emilkowalski Hate to tag open source maintainers, but thought maybe you missed this -- any chance you could provide a release with the fix for the issue here? I've been pinned to v1.4.3 for a couple of months now.

https://www.npmjs.com/package/@jose-donato/sonner

I forked from latest main and published as a temporary fix in the meantime
