### ISSUE TITLE
Accidental publish of new versions?

### ISSUE THREAD

**Issue by TotomInc** [emilkowalski/sonner#381]
### Describe the feature / bug 📝:

According to npm, there has been something strange on the versioning.

![CleanShot 2024-03-21 at 11 12 41](https://github.com/emilkowalski/sonner/assets/9285210/a21fdba8-e645-4004-babf-16ff2face80e)

The package.json hasn't been updated and I am not able to find any commit which reflects a publish / bump.

The latest GItHub release is for 1.4.3.

Is there something broken about publishing?

### Steps to reproduce the bug 🔁:

None.

**Comment by emilkowalski** [comment]
I just posted a GitHub release right now, forgot about it. This should've been just one version bump, my bad!
