### ISSUE TITLE
Icons missing when using promises

### ISSUE THREAD

**Issue by SimonLeclere** [emilkowalski/sonner#388]
### Describe the feature / bug 📝:

When using toast.promise, the success or error icon is not displayed after resolving the promise. I saw that you had merged a pull request that fixed this behavior but I don't know why, I can't get it to work :(((

I'm using v1.4.41

**Comment by SimonLeclere** [comment]
Okay, I just found the problem. That's some weird behavior...

This code displays the icons : 
```js
const prom = new Promise((resolve, reject) => {
              setTimeout(() => {
                resolve({ name: 'toast' }); 
              }, 1000);
            })
          
            toast.promise(prom, {
              loading: 'Loading...',
              success: (data) => {
                return `${data.name} toast has been added`;
              },
              error: 'Error',
            });
```

But this code doesn't: 
```js
const prom = new Promise((resolve, reject) => {
              setTimeout(() => {
                resolve({ name: 'toast' }); 
              }, 1000);
            })
          
            toast.promise(prom, {
              loading: 'Loading...',
              success: (data) => {
                return <>{data.name} toast has been added</>;
              },
              error: <>Error</>,
            });
```

**Comment by matheusg-turing** [comment]
I'm facing the same issue, but neither of suggestions above from @SimonLeclere worked for me, it only shows the text without the icon.

Also I notice that seems to still rendering the loading spinner even after showing the success message:
![image](https://github.com/user-attachments/assets/5388c41a-a9a1-407c-b370-c376fdfea833)

**Comment by SimonLeclere** [comment]
Hey, you should provide a code snippet with the description of your problem so we can try to reproduce it

**Comment by SimonLeclere** [comment]
Hey, you should provide a code snippet with the description of your problem so we can try to reproduce it :)

**Comment by matheusg-turing** [comment]
Hey, sorry, it's literally the same snippet you provided; I just copied and pasted:

```ts
const prom = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve({ name: 'toast' })
      }, 1000)
    })

    toast.promise(prom, {
      loading: 'Loading...',
      success: (data) => {
        return `${data.name} toast has been added`
      },
      error: 'Error',
    })
```

Quick demo:

https://github.com/user-attachments/assets/8a046a4c-aecc-414c-91e1-0baa23f1dcaa

I was using v1.4.1, tried to update to yours (1.4.41), and now I'm using 1.5.1, but the success icon doesn't show in any of them, even as a string or as ReactNode. I also tried to override the success icon to test (I'm using Lucide to display icons):

```tsx
<Toaster theme={theme} icons={{ success: <Icon name="Magnet" /> }} />
```

And it works fine when I call directly `toast.success`, meaning I can well see the custom icon, but it still doesn't show on `toast.promise`.

**Comment by jzhou891** [comment]
can we reopen this? I tried on `1.7.2` and the success/error icon is not showing up for promises and loading toasts
