### ISSUE TITLE
addEventListener is not implemented in older versions of Safari.

### ISSUE THREAD

**Issue by anson0370** [emilkowalski/sonner#395]
### Describe the feature / bug 📝:

Strictly speaking, it's not a bug but a compatibility issue. `window.matchMedia().addEventListener` does not exist in Safari versions less than 5.0.
`next-themes` has addressed this issue by using the now deprecated `addListener` API. https://github.com/pacocoursey/next-themes/pull/24
I'm not sure if you think this issue needs to be resolved?

### Steps to reproduce the bug 🔁:

1. Use sonner in Safari versions less than 5.0.

**Comment by emilkowalski** [comment]
AFAIK Safari 5.0 > is from 2010, let's stick to `addEventListener`.

**Comment by gunnartorfis** [comment]
@emilkowalski addEventListener is only supported in Safari on iOS 14.0+. iOS 14 was released 2020 so this is actually quite common. We have over 100 users experiencing a crash because of this. 

What other approaches are available? Would it be possible to force a color-scheme for iOS <= 13 somehow?
