### ISSUE TITLE
Toast width

### ISSUE THREAD

**Issue by developedbytoby** [emilkowalski/sonner#4]
![image](https://user-images.githubusercontent.com/77097223/221032828-606f3373-a8b7-4a99-94b9-307294454caa.png)

Rather than having a fixed width, I think it would make more sense to instead apply padding to the element, or at least have this as an option. This way, if the toast only contained a small amount of text, it would fit the toast element better.

**Comment by emilkowalski** [comment]
The reason why they are all equal width is to make the stacking look good, otherwise we would get something like this:
<img width="413" alt="CleanShot 2023-02-24 at 11 24 53@2x" src="https://user-images.githubusercontent.com/36730035/221155176-6c5e1553-08b3-4e87-8650-1f08ac249738.png">

This won't be a problem when used in the expanded mode tho.

You can change the styling of all toasts like this, this way it will hug the content and have 16px of padding which you can change as well.
```jsx
<Toaster
  toastOptions={{
    style: {
      width: 'fit-content',
    },
  }}
/>
```

**Comment by columk1** [comment]
With a centered position option, changing the width to an intrinsic value throws the centering off. Adding flex rules to the Toaster will keep it centered.
```jsx
<Toaster
  position="bottom-center"
  className="flex justify-center"
  toastOptions={{ className: 'w-fit' }}
/>
```

**Comment by d5br5** [comment]
> With a centered position option, changing the width to an intrinsic value throws the centering off. Adding flex rules to the Toaster will keep it centered.
> 
> <Toaster
>   position="bottom-center"
>   className="flex justify-center"
>   toastOptions={{ className: 'w-fit' }}
> />

I will bow in your direction every day. @columk1

**Comment by TurtleP** [comment]
@columk1 this doesn't seem to work. I'm not sure if it's due to the newer version of sonner I am using or not using tailwind.

```
            <Toaster
                position="top-center"
                richColors
                className="flex justify-center"
                toastOptions={{ style: { width: 'fit-content' } }}
            />
```

This does fit the text content, but it's not centering toasts as expected.

**Comment by SadhuG** [comment]
` <Toaster
          position="bottom-center"
          className="flex justify-center"
          toastOptions={{
            style: { width: "fit-content", marginInline: "auto" },
          }}
  />`

@TurtleP  This one fixes the centring of toast.

**Comment by TurtleP** [comment]
@SadhuG I placed your code into my Toaster, but it's still offset. Is there something I'm missing? My root div element does `display: flex`.

**Comment by SadhuG** [comment]
Yes, I used tailwind. Did your solution worked

**Comment by columk1** [comment]
> [@columk1](https://github.com/columk1) this doesn't seem to work. I'm not sure if it's due to the newer version of sonner I am using or not using tailwind.

It could it be the missing Tailwind classes if you don't have those utility classes in your CSS. Try this:
```jsx
<Toaster
  position="top-center"
  style={{
    display: 'flex', justifyContent: 'center' 
  }}
  toastOptions={{
    style: { width: 'fit-content'},
  }}
/>
```

However it does seem like the latest Sonner version is working differently. This method works above 600px, but below that the toast becomes full-width again.
