### ISSUE TITLE
icons prop does not exist

### ISSUE THREAD

**Issue by RicSala** [emilkowalski/sonner#405]
### Describe the feature / bug 📝:

I am following the docs:

![image](https://github.com/emilkowalski/sonner/assets/28371562/5ada065c-31a1-4506-99b0-607236341f89)

And icons prop seems to not be there:

<img width="702" alt="image" src="https://github.com/emilkowalski/sonner/assets/28371562/9fcdd8ed-e2ec-4219-9622-a74ae88a53c6">

**Comment by Willem-Jaap** [comment]
Are you on the latest version?

**Comment by noudadrichem** [comment]
I have the same issue. It's not in the props type as well 
![image](https://github.com/emilkowalski/sonner/assets/16288476/119ff375-4cf3-4752-a7af-6ca23b95cc1c)


Version used is 1.4.0 installed today.

**Comment by emilkowalski** [comment]
You need `1.4.41`
