### ISSUE TITLE
offset requires a number, but only works if you pass string

### ISSUE THREAD

**Issue by bryanbarrios** [emilkowalski/sonner#41]
### Bug description

Currently, if we pass a number to the `offset`, it'll break the position of the Toast because it isn't the type it expects.

![Screenshot 2023-03-15 at 14 03 31](https://user-images.githubusercontent.com/57823539/225431014-6d186bbf-2842-4d7f-bffd-352016761faf.png)

### How to reproduce

Pass a number to the `offset`.

```tsx
<Toaster offset={12} />
```

### Expected behavior

`offset` should be set according to the number value passed to it.

### Environment

```text
Operating System:
  Platform: darwin
  Arch: arm64
Binaries:
  Node: 18.12.0
  pnpm: 7.14.2
Relevant packages:
  sonner: 0.2.0
  next: 13.2.4
  react: 18.2.0
  react-dom: 18.2.0
```

**Comment by emilkowalski** [comment]
This has been fixed in #31, which will be released to npm soon.
