### ISSUE TITLE
Just rendering the last 3 notifications 

### ISSUE THREAD

**Issue by iamvermajayant** [emilkowalski/sonner#410]
### Describe the feature / bug 📝:

Can we modify the number of toast we can see on the screen 
suppose we have 10 notifications so we are just seeing the last 3 of it how to see all on screen

**Comment by sthasam2** [comment]
Please look into the visibleToasts prop mentioned here

https://sonner.emilkowal.ski/toaster

**Comment by emilkowalski** [comment]
Yup, you'll need the `visibleToasts` prop that @sthasam2 mentioned!
