### ISSUE TITLE
How to add description in a promise

### ISSUE THREAD

**Issue by Noname968** [emilkowalski/sonner#413]
### Describe the feature  📝:

How to add description to a promise success or error.

**Comment by mridul1024** [comment]
Hi, 
I just look through the code and the return types for both success and error is defined as `React.ReactNode | string`. Given that you wish to display a header field that is followed by a description, you may attempt building your structure by enclosing it within an element and returning it as a response. The promise functionality does not have its own description field.

Example: 
````
toast.promise<{
  header: string;
  description: string;
}>(
  Promise.resolve({
    header: "Notification",
    description: "Test Description",
  }),
  {
    loading: "Loading...",
    success: (data: { header: string; description: string }) => {
      return (
        <div>
          <div className="font-semibold">{data.header}</div>
          <p>{data.description}</p>
        </div>
      );
    },
    error: "Error"
  }
);
````

I hope this answers your query 😇
