### ISSUE TITLE
Do we have Figma components?

### ISSUE THREAD

**Issue by Artaherzadeh** [emilkowalski/sonner#416]
Hi
We are using this package and wanted to know if we have the components on Figma.

**Comment by gurvirsinghbaraich** [comment]
You can also try the toast-ease library (https://www.npmjs.com/package/toast-ease). The toast-ease library can do what sonner cannot do. The library is at v0.0.1.

### Advantages
- You cannot server render a toast, but with toast-ease you can do it.

### Video Demo

https://github.com/emilkowalski/sonner/assets/161711856/8573c4db-95b8-4a5a-a095-96b7412168f0

**Comment by emilkowalski** [comment]
Unfortunately not, is that something more people would want do you think? I might make a simple Figma file if so.
