### ISSUE TITLE
Bug: an issue with toasts description

### ISSUE THREAD

**Issue by hesamhoseinkhani** [emilkowalski/sonner#428]
### Describe the feature / bug 📝:

You can't just pass a custom component as a description to your toast.

### Steps to reproduce the bug 🔁:

1. Try to create a toast and pass a custom component to it's description, it will show you [object object]

Something like this:
toast("toast name", { description: <CustomComponent /> })

**Comment by hesamhoseinkhani** [comment]
The thing is it just accepts descriptions as strings whether an actual string or an element inside the string, actually, we can pass the custom components with **renderToString** function in react but I don't really feel good about using that in this case...

**Comment by n-valchev** [comment]
As far as I can see, this has already been fixed by #387 but is yet to be released.
