### ISSUE TITLE
a way to disable auto-dismiss?

### ISSUE THREAD

**Issue by TheMikeyRoss** [emilkowalski/sonner#429]
Is there a way to disable the auto-dismiss? I mean I can use an extremely long duration. But I'm using the sonner for cookie consent and I don't want the toast to go away unless the user clicks on "agree" (which will dismiss the toast)

**Comment by zaaakher** [comment]
As mentioned [here](https://github.com/emilkowalski/sonner/issues/327#issuecomment-1928635953), you'll have to use Javascripts'  `Infinity` ([read more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity))

```js
createSonner("Something", {
    duration: Infinity,
});
