### ISSUE TITLE
Bundle size could be improved 300% by getting rid of DOMPurify

### ISSUE THREAD

**Issue by AlessioGr** [emilkowalski/sonner#438]
[Payload](https://github.com/payloadcms/payload) is currently using react-toastify. Would love to switch to sonner, but it comes with a noticeable bundle size increase - and we are trying to keep it low.

So I did some research as for _why_ sonner's bundle size is larger - the source code itself is super nice and clean. We'll consider including the src of a [trimmed version of sonner](https://github.com/AlessioGr/sonner-zero) within payload and using that for now, to benefit from the smaller bundle size. Here are my findings:

## DOMPurify

The DOMPurify package TRIPLES your bundle size. Removing DOMPurify from your codebase brings down the gzipped bundled js size from 14kb to 5kb.

And all it does is sanitize input strings of toast titles and descriptions, IF html provided. Within our app, we know we will never want to toast html, and we have full control over what we're toasting out. If we do want to toast out html, we can sanitize it ourselves.

It might be worth the bundle bundle size improvement to consider removing it and, in your docs, advising the users who provide html to sanitize it themselves. They might already have a library for html sanitization installed & bundled in their project!

**Comment by emilkowalski** [comment]
Thanks @AlessioGr, merged a PR without looking at the bundle size of the package, I just fixed it in #439

**Comment by AlessioGr** [comment]
That was fast, thank you!
