### ISSUE TITLE
Issue with expand Prop

### ISSUE THREAD

**Issue by simply-arko** [emilkowalski/sonner#448]
### Describe the feature / bug 📝:
The expand prop can only be set to `<Toaster />` which results in expanded view of all the toasts all across the app. I don't want that. Instead I want only for a specific toast to have the expanded view. How can I achieve this? I'm able to figure it out, can anyone please help?

### Steps to reproduce the bug 🔁:

1. Setup the app as described in the docs.
2. Try to fire a toast from any component.
3. It does not show any prop called `expand`.

**Comment by emilkowalski** [comment]
This is not supported and won't be. YYou can only choose to expand all or none.
