### ISSUE TITLE
[v1.5.0] Lost layer-by-layer toast disappear effect in `v1.5.0`

### ISSUE THREAD

**Issue by hoangnhan2ka3** [emilkowalski/sonner#451]
### Describe the feature / bug 📝:

Lost layer-by-layer toast disappear effect in`v1.5.0`. Everything is okay with `<=v1.4.41`.
I don't plan on version `1.4.41` because `v1.5` has some new useful features added.

### Steps to reproduce the bug 🔁:

1. Update `sonner` to `v1.5.0`.

Expected behavior: https://sonner-r9g0najdf-emilkowalski-s-team.vercel.app/

Latest version behavior: https://sonner.emilkowal.ski/

2. Use `Default` mode (not `Expanded` mode) and wait til it disappear to see the effect.

**Comment by emilkowalski** [comment]
Fixed in #461

**Comment by hoangnhan2ka3** [comment]
When can we have the update sir?
