### ISSUE TITLE
Provide a way to have a custom close icon

### ISSUE THREAD

**Issue by deadeagle63** [emilkowalski/sonner#454]
### Describe the feature / bug 📝:

Currently there is no way to my knowledge of overriding the close icon, the only icon available for override are
<img width="555" alt="image" src="https://github.com/emilkowalski/sonner/assets/56412825/28c195bb-c640-4bc3-8992-cbac70ff9cd1">

### Steps to reproduce the bug 🔁:

1. Create toast provider
2. Try to assign custom icons
3. Close icon not present in the list

**Comment by TheMikeyRoss** [comment]
just out of curiosity , what icon would you use?

**Comment by deadeagle63** [comment]
@TheMikeyRoss just anything really, but right now I just need to swap in our custom one from the UI/UX designer :)
