### ISSUE TITLE
bug: Toaster width is not fit

### ISSUE THREAD

**Issue by araaso-dev** [emilkowalski/sonner#472]
### Describe the feature / bug 📝:

The Toast doesn't have a width that it's fit to every kind of length of text.

![image](https://github.com/user-attachments/assets/8c11e09a-cb12-46fb-a72e-16ba4e98443a)

### Steps to reproduce the bug 🔁:

      toast.error(
        "Please ensure all services have a quantity greater than 0 and a valid service selected."
      );

**Comment by lekhanh2099** [comment]
What is new? I have the same issue here.

**Comment by emilkowalski** [comment]
Can you provide a codesandbox demo with reproduction? I'm unable to reproduce it.

![CleanShot 2024-11-02 at 17 20 22@2x](https://github.com/user-attachments/assets/70e2982e-0d2e-484b-a200-5b3ea51feaa8)

**Comment by araaso-dev** [comment]
I think the bug is fixed now

**Comment by ming-yop** [comment]
what if I want to have white-space: nowrap? how can I make the width always fit the content?
