### ISSUE TITLE
Possibility for a custom toast ID

### ISSUE THREAD

**Issue by sunwrobert** [emilkowalski/sonner#49]
Is there anyway we could create a toast with a custom ID? Would be a very useful feature as well when we want to specifically create toasts with certain IDs and dismiss them at a later time, without us having to store the IDs in some state to map them back to the auto-generated sonner ID

**Comment by emilkowalski** [comment]
This has been fixed in #51. Keep in mind that 2 toats can't have the same id, the animation will be incorrect otherwise.
