### ISSUE TITLE
Customization via className prop doesn't work

### ISSUE THREAD

**Issue by jonasmerlin** [emilkowalski/sonner#5]
Neither when passing it to the `<Toast />` component nor when using it inside the options of the `toast()` call does the `className` options do anything. Tested it with both Tailwind classes as well as my own globally defined ones. The style of the toast stays the same. `style` works though!

**Comment by joaom00** [comment]
It seems to work for me, how are you using it? one thing to pay attention to is that your style imports must come after the package import

**Comment by jonasmerlin** [comment]
@joaom00 I'm using it with Next.js and Tailwind. There, even if I move the `<Toaster />` component import into my `_app.tsx` file and only import my `globals.css` afterwards it doesn't work. (Sorry if you're not familiar with the setup, it's basically: I import both the component and the styles "globally" for my app and the package comes before the styles.)

**Comment by emilkowalski** [comment]
@jonasmerlin Are the classnames in the html and just overriden by library css or are they not there at all?

**Comment by jonasmerlin** [comment]
@emilkowalski They are present in the html, so they get overridden.

**Comment by emilkowalski** [comment]
Could you create a codesandbox/github repo with an example please?

**Comment by BaileySimrell** [comment]
@emilkowalski chiming in here as I'm experiencing something similar. The library & default component styles are beautiful! I'm just trying to get them working with our custom font (Space Grotesk) and update the color slightly via Tailwind and am not having any luck 

Set up on Next and Tailwind

Here's the code for that page: https://gist.github.com/BaileySimrell/7d7480ea0bff9c2d4bdd528c9eb4af25

**Comment by emilkowalski** [comment]
You'd need to use inline styling via the `style` prop or `!important` for the classes to override it.
Further customization will be possible in the future by rendering a fully custom toast.

**Comment by joaom00** [comment]
i think can be added `:where` pseudo-class to styles, as it has 0 specificity, so we don't need to rely on `!important` in classes to override styles a bit

**Comment by emilkowalski** [comment]
> I think can be added `:where` pseudo-class to styles, as it has 0 specificity, so we don't need to rely on `!important` in classes to override styles a bit

Could you elaborate? I’m unfamiliar with this

**Comment by BaileySimrell** [comment]
> You'd need to use inline styling via the `style` prop or `!important` for the classes to override it. Further customization will be possible in the future by rendering a fully custom toast.

Can confirm this works:
`toast.message('Event has been created', {
   description: 'Monday, January 3rd at 6:00pm',
   style: { fontFamily: "'Space Grotesk', sans-serif", color: '#1c1d21'},
})`

Thank you! @emilkowalski

**Comment by BaileySimrell** [comment]
> > You'd need to use inline styling via the `style` prop or `!important` for the classes to override it. Further customization will be possible in the future by rendering a fully custom toast.
> 
> Can confirm this works: `toast.message('Event has been created', { description: 'Monday, January 3rd at 6:00pm', style: { fontFamily: "'Space Grotesk', sans-serif", color: '#1c1d21'}, })`
> 
> Thank you! @emilkowalski

Ok following up on this again @emilkowalski ... using the style property works with `toast.message`, however it doesn't work with `toast.promise`

**Comment by joaom00** [comment]
> Could you elaborate?

Using `:where([data-sonner-toast])` instead of `[data-sonner-toast]` will allow consumers to easily override lib styles using CSS frameworks similar to tailwind or using their own classes because `:where` has 0 specificity, even if lib styles come later they will be overridden by consumer styles

**Comment by BaileySimrell** [comment]
@joaom00 is right! Adding the following code to `globals.css` worked for me

```
/* toast font override */
:where([data-sonner-toast]) {
    font-family: 'Space Grotesk', sans-serif;
    color: #1c1d21;
}
```

**Comment by emilkowalski** [comment]
You should try to use the `style` option as much as possible as that's the easiest way to override the default styling, classes need a higher specificity level which can be achieved with `!important` or just adding more selectors for example. 
That's not ideal when you are using Sonner with tailwind for example, but in that case you probably want to customize the toast even more (lose the default styling) which the [headless](https://github.com/emilkowalski/sonner#headless) option allows.

**Comment by BorisZubchenko** [comment]
Tailwind example with higher selector specificity:

```css
@layer base {
  [data-sonner-toaster][data-sonner-toaster] li {
    @apply bg-red-500;
  }
}
```

**Comment by simbesh** [comment]
@emilkowalski I see Sonner is dependency free however it might be beneficial to use **tailwind-merge** instead of the manual concatenation of class names here https://github.com/emilkowalski/sonner/blob/3295698d540ee06340b8e6640887ae936693e96d/src/index.tsx#L212
which should? resolve the tailwind style conflicts and need for setting !important
