### ISSUE TITLE
toast initial-height

### ISSUE THREAD

**Issue by b1ngx** [emilkowalski/sonner#50]
toast title initial-height is affected by line-height, causing layout shifts when hover.

**Comment by emilkowalski** [comment]
Could you create a reproduction on https://codesandbox.io/ or https://stackblitz.com/? Thanks!

**Comment by b1ngx** [comment]
https://stackblitz.com/edit/vitejs-vite-ltgfey

**Comment by emilkowalski** [comment]
This has been fixed in #53
