### ISSUE TITLE
Update toast with duration opt is not working

### ISSUE THREAD

**Issue by kaitoukid-1412** [emilkowalski/sonner#509]
`sonner v1.7.0`

```jsx
import { Toaster, toast } from 'sonner';

const CHANGE_ME_TO_TRIGGER_TOAST = 18;

function App() {
  const id = toast(`duration:Infinity ${CHANGE_ME_TO_TRIGGER_TOAST}`, {
    duration: Infinity, // Hello
  });

  return (
    <>
      <Toaster />
      <button
        onClick={() =>
          toast(`Updated toast ${id}`, {
            id,
            duration: 3000, // Word
            description: id,
          })
        }
      >
        Updating toast and duration has no effect
      </button>
    </>
  );
}

export default App;
```

See: https://stackblitz.com/edit/vitejs-vite-weca9x?file=src%2FApp.tsx

**Comment by emilkowalski** [comment]
I'm not exactly sure what you are trying to achieve here. What is this supposed to do `duration:Infinity`?

**Comment by jdhenry08** [comment]
I am having this problem too - when I create a toast with duration: Infinity, if I update the toast later and set the duration to a value other than Infinity, the toast never dismisses.

**Comment by Pedro-vk** [comment]
@kaitoukid-1412 you market as "Closed" is it fixed?
I'm having the same issue

**Comment by nosu-park** [comment]
use setTimeout

```
const toastId = toast(`Infinity toast`, {
  duration: Infinity
});

toast(`Updated toast`, {
  id: toastId,
})

setTimeout(() => {
  toast.dismiss(toastId);
}, 3000);
```

**Comment by ryanelian** [comment]
I don't think setTimout has the same effect as the original dismiss logic.

The original dismiss logic stops the component from dismissing when the user hovers over the component.

If you use setTimeout, it will dismiss regardless if the user is currently hovering over the toast.

**Comment by aabuhijleh** [comment]
> it is not a bug, it is a feature

It looks like a bug to me 🤷
