### ISSUE TITLE
Regression: Headless version is not passing role and aria attributes

### ISSUE THREAD

**Issue by cloud-walker** [emilkowalski/sonner#519]
From the v1.6 onward the toast.custom API doesn't apply role and aria attributes anymore. Its a bug?

**Comment by FujiHaruka** [comment]
I think this is an intentional change:
https://github.com/emilkowalski/sonner/pull/436

**Comment by emilkowalski** [comment]
Yes this is an intentional change, but I'm open to updating it. If you think there's a better approach, please open an issue with an explanation.
