### ISSUE TITLE
Toast with image is shaking when hovered

### ISSUE THREAD

**Issue by m4xshen** [emilkowalski/sonner#521]
## Description

- When I `toast` an `img` component, the UI starts shaking when cursor hovers on it.
- The shaking behavior only happens for the first toast.

## Screenshot

https://github.com/user-attachments/assets/45a9c8b5-d09a-4c48-997e-829bc97bbbb0

## Steps to reproduce

1. Clone this repo: https://github.com/m4xshen/toast-testing
2. `pnpm i`
3. `pnpm dev`
4. Visit http://localhost:3000/
5. Trigger the toast
6. Hover cursor on it

**Comment by multivoltage** [comment]
Did you try something like:
```js
<img src="/vercel.svg" style={{ width: 200, height: 200}} />
```

For me it works

**Comment by m4xshen** [comment]
It works. Thanks!
