### ISSUE TITLE
click close button will cause dialog close

### ISSUE THREAD

**Issue by tjx666** [emilkowalski/sonner#522]
Any way to make the close buton e.stopPropagation() and event.preventDefault(); ?

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/bfc1fed9-a04d-494e-b8bb-ac5ca8257739">

**Comment by emilkowalski** [comment]
Interacting with any element outside of the dialog closes it, which is expected. I'd suggest you to just not include the X icon in the toast.

**Comment by tjx666** [comment]
Can't we provide a option to stopPropagation when close button click?
