### ISSUE TITLE
It's works in Vuejs

### ISSUE THREAD

**Issue by riderx** [emilkowalski/sonner#54]
Just to share that I tried to translate sooner in Vue.js with gpt-4, spent 10h on it and couldn't make it properly.

Then I found out : https://github.com/devilwjp/veaury
And tried and in 5 min it worked.
So, Your plugin is now used in a Vue 3 app: https://github.com/Cap-go/capgo

Thanks for the work <3

**Comment by emilkowalski** [comment]
That's great to hear!

**Comment by wobsoriano** [comment]
Just need some polishing and it’ll be ready to use

https://github.com/wobsoriano/sonner-vue
