### ISSUE TITLE
Update toast message during promise

### ISSUE THREAD

**Issue by eqan** [emilkowalski/sonner#59]
Hi first of all i would like to appreciate your efforts in developing such a beautiful notification mechanism, hopefully the project would grow into something more spectacular.

I wanted to ask if the toast message during its promise can be changed for example lets say data is being uploaded to 3 different servers i would like the toast to showcase on which endpoints the data has been uploaded, is it possible to showcase that??

**Comment by emilkowalski** [comment]
Fixed in #75
