### ISSUE TITLE
change peerDeps to allow for react 17

### ISSUE THREAD

**Issue by DimitarChristoff** [emilkowalski/sonner#71]
Is there any hard reason for it? It seems to work fine but npm is not liking the requirement when run under a react 17 codebase. Thanks in advance.

**Comment by emilkowalski** [comment]
Is there any reason for not updating your app to React 18? I'd like to keep the peerDeps at 18+

**Comment by DimitarChristoff** [comment]
It's a huge codebase as platform for 30+ apps and the changes (in particular, dev mode hook rerenders etc) cause a huge risk, don't think we can update any time soon. 

Worst case, I may fork and republish this as a namespaced package and somehow keep it in sync with yours

**Comment by emilkowalski** [comment]
I see, I'd waant to keep the peerDeps at 18+ so feel free to fork!

**Comment by pranavgoel29** [comment]
Were you able to make it work with React 17?
I want to use this with react 16 🫠

**Comment by FunnyPhantom** [comment]
For anyone whose interested:

This can be achieved via adding "override" field in the package.json:
```
"overrides": {
    "sonner": {
      "react": "$react",
      "react-dom": "$react-dom"
    }
  }
  ```
  
  This can ensure whenever you upgrade your react version, this works as well without the need to fork.
