### ISSUE TITLE
Proposal to Contribute Documentation for Sonner

### ISSUE THREAD

**Issue by Chinedu19** [emilkowalski/sonner#78]
Hello,

I've recently come across Sonner and found it to be an extremely useful toast component for React applications. However, I noticed that there could be more comprehensive documentation that elaborates on its features, use-cases, and provides more detailed setup and usage instructions. I believe this would be immensely beneficial to developers who are new to Sonner or those who would like to fully utilize its functionalities.

I have considerable experience with React and would love to contribute to enhancing the documentation for this project.

Here's what I propose to work on:

1. **Getting Started Guide**: A step-by-step guide on how to install and start using Sonner.
2. **Detailed Features Overview**: A comprehensive explanation of all Sonner features, including customization, positioning, expanding, color options, the close button, and headless usage.
3. **Example Usage**: A section demonstrating how to use Sonner in common use-cases, such as displaying success, error, or informational notifications. 
4. **API Reference**: A detailed breakdown of all available methods, props, and options. 
5. **Troubleshooting FAQ**: A section dedicated to helping users troubleshoot common issues.

Please let me know if this is something you'd be interested in, and if so, if there are any specific guidelines or prerequisites I should follow.

Looking forward to your feedback.

Best regards,
Augustine

**Comment by emilkowalski** [comment]
This would be amazing! I suggest creating a new project in this repo and using Nextra for the documenation.

**Comment by Chinedu19** [comment]
Great.

I'd begin working on it.

**Comment by amosbastian** [comment]
I'm especially interested in seeing how to create a custom toast with the promise functionality

I'm currently using a custom function like so:

```ts
export function toast({
  action,
  className,
  data,
  description,
  title,
  variant,
}: {
  action?: React.ReactNode;
  className?: string;
  data?: Parameters<typeof sonnerToast>[1];
  description?: string;
  title?: string;
} & VariantProps<typeof toastVariants>) {
  // TODO: Do some stuff with promises here
  return sonnerToast.custom((t) => (
    <div className={classnames(toastVariants({ variant }), className)}>
      <div className="grid gap-1">
        {title ? <p className="text-foreground text-sm font-semibold">{title}</p> : null}
        {description ? <p className="text-sm opacity-90">{description}</p> : null}
      </div>
      {action}
      <button
        onClick={() => sonnerToast.dismiss(t)}
        className="text-foreground/50 hover:text-foreground absolute right-2 top-2 rounded-md p-1 opacity-0 transition-opacity focus:opacity-100 focus:outline-none focus:ring-2 group-hover:opacity-100 group-[.destructive]:text-red-300 group-[.destructive]:hover:text-red-50 group-[.destructive]:focus:ring-red-400 group-[.destructive]:focus:ring-offset-red-600"
      >
        <X className="h-4 w-4" />
      </button>
    </div>
  ));
}
```
