### ISSUE TITLE
Possibility for pass position in toast.custom()

### ISSUE THREAD

**Issue by jfelipebc** [emilkowalski/sonner#79]
Hi, There is a possibility to pass the position of toast through toast.custom.
```
toast.custom(
  (t) => (
    <div>Hello world</div>
  ),
  {
      ...
      position: top-center, // top-left, top-center, top-right, bottom-left, bottom-center, bottom-right
  }
);
```

**Comment by emilkowalski** [comment]
We won't be suporting multiple positions at once unfortunately.

**Comment by nanwy** [comment]
> We won't be suporting multiple positions at once unfortunately.

Can this be considered as a new feature? I think I will find it very useful, especially when I'm using functional calls to display toast messages。like 
```
      if (data?.code === 200) {
        toast.error(`status：${data?.code}`, {
          description: data.message,
          position: "top-center"
        })
        return data.data
      }
```
