### ISSUE TITLE
Tests 

### ISSUE THREAD

**Issue by emilkowalski** [emilkowalski/sonner#8]
Some e2e tests to avoid regression would be useful.
Here's an example of how that might look like - https://github.com/pacocoursey/cmdk/tree/main/test.

**Comment by lirbre** [comment]
Hey! 

Starting to write some e2e - can I stick with [cmdk playwright config](https://github.com/pacocoursey/cmdk/blob/main/playwright.config.ts)?

**Comment by emilkowalski** [comment]
Yes!

**Comment by lirbre** [comment]
@emilkowalski finished the config - removed the draft status from PR. 

would you mind to write something like a priority list to e2e testing? I'll be adding some of them when I had more time :)

**Comment by lilpolymath** [comment]
> @emilkowalski finished the config - removed the draft status from [PR](https://github.com/emilkowalski/sonner/pull/10).
> 
> would you mind to write something like a priority list to e2e testing? I'll be adding some of them when I had more time :)

+1. I think this would be great just in case other people want to contribute to the test writing.

I think it would be great if they are made into issues or added to a project board.
