### ISSUE TITLE
Update existing toast title in `toast.promise` side effects

### ISSUE THREAD

**Issue by joaom00** [emilkowalski/sonner#82]
I would like to create some kind of toast confirmation. My first attempt was to update the toast by passing an id

```jsx
const id = toast("Are you sure...", {
      action: {
        label: "Save",
        onClick: () => {
          toast.promise(promise, {
            id,
            loading: "Loading...",
            success: "Saved",
            error: "Something went wrong"
          });
        }
      }
```

The first error with this is that when clicking on "Save" the toast is closed and there seems to be no way to disable this. The second error is the title `Are you sure...` has not been updated to `Loading...`.

### Suggested Solution

I think this can be handled in two ways:

1.  Provide a `toast.confirm` API for these cases
2. Possibility to update an existing toast by passing an `id` to `options`.

I would say that the second option is preferable because it offers more flexibility. For example, if the second option is implemented, it would be nice if the toast promise options could return an object to update the toast

```jsx
    const id = toast("Are you sure...", {
      action: {
        label: "Save",
        onClick: () => {
          toast.promise(promise, {
            id,
            loading: "Loading...",
            success: () => {
              return {
                title: 'Saved',
                action: {
                  label: "Undo",
                  onClick: () => { ... }
              }
            },
            error: "Something went wrong"
          });
        }
      }
    });
```

**Comment by emilkowalski** [comment]
Maybe we could refactor it so that we can do`e.preventDefault` in the action `onClick` to not close the toast and then update the toast as [described here](https://github.com/emilkowalski/sonner)?

**Comment by joaom00** [comment]
> Maybe we could refactor it so that we can do e.preventDefault in the action onClick to not close the toast

Yeah, it would be nice

> then update the toast as [described here](https://github.com/emilkowalski/sonner)?

I don't think so. When using the `toast.promise` the title is not updated. It might work if there was a `toast.loading` but I would like to use the `toast.promise` because it already handle the loading, success and error states. I would have to do all the `.then().catch()` stuff myself.

I think it's a specific problem in how the title of the promise toast is handled. Instead of using a local variable, it could update the title of the toast. What do you think?

**Comment by emilkowalski** [comment]
That sounds good to me!

**Comment by joaom00** [comment]
Okay, I'll update the title to describe more precisely what's the issue
