### ISSUE TITLE
Default custom component

### ISSUE THREAD

**Issue by dusanmarsa** [emilkowalski/sonner#83]
## Feature proposal

We have a option to add custom component to the toast with 

```tsx
toast.custom(
    <div>
        {/* Custom stuff */}
    </div>
)
``` 

What if we would be able to have default custom component from the Root provider? For example

```tsx
import { Toaster, toast } from 'sonner';

const Custom = (toasterProps: SomeToasterProps) => {
    return (
        <div>
            {/* Custom stuff */}
        </div>
    )
}

const App = () => {
  return (
    <div>
      <Toaster custom={Custom} />
      <button onClick={() => toast('I am using custom toast')}>Give me a toast</button>
    </div>
  );
}
``` 

The default component could inherit props from the library, and then for example even the `toast.error`, would use the custom toast. I had to use the `react-toastify` recently, and I had to create custom function to reuse the custom component everywhere. I believe it's the same here.

**Comment by emilkowalski** [comment]
We won't be supporting it for now.
