### ISSUE TITLE
Toaster incorrectly calculates its height in promise variant when a long title is passed to it

### ISSUE THREAD

**Issue by pkorsakov1** [emilkowalski/sonner#85]
https://github.com/emilkowalski/sonner/assets/134369911/5025608d-3605-4739-b9d6-35acafba1852

**Comment by joaom00** [comment]
What version are you using?

**Comment by pkorsakov1** [comment]
> Which version are you using?

0.4.0

**Comment by joaom00** [comment]
This was fixed in #75 but it looks like it's not in npm. Locally everything seems to work


https://github.com/emilkowalski/sonner/assets/48808846/e8db72f8-d085-4194-9728-a1aa67dc95fd

**Comment by emilkowalski** [comment]
This should be fixed in the newest release!
