### ISSUE TITLE
toast.promise duration

### ISSUE THREAD

**Issue by enesusta** [emilkowalski/sonner#89]
Can we add duration prop to toast.promise?

for ex:

```ts
      const promise = () => registerNewPatient(req);

      toast.promise(promise, {
        loading: 'Hasta kayıt ediliyor',
        success: data => {
          const patientId = data.patientId;
          const fullname = data.fullname;
          const sleep = () => new Promise(resolve => setTimeout(resolve, 5000));
          toast.promise(sleep, {
            loading: '5 saniye içinde hasta detay sayfasına yönlendiriliyor olacaksınız...',
            success: data => {
              history(
                `/patient/${patientId}?step=treatment&treatment=1&payment=1&new_register=true`,
              );
              return null
              // return `Tablo alanı üzerinde sağ tıklayarak yeni tedavi kaydı oluşturabilirsiniz`;
            },
            error: 'Error',
          });

          return `${fullname} isimli hasta başarı ile kaydedildi`;
        },
        error: 'Error',
      });
```

I want to show success toast messages longer than it is. But I don't want to set global duration. 

```ts
toast.promise(promise, {}, { duration: 5000 })
```

thank you to create this library.

**Comment by HananoshikaYomaru** [comment]
There are two ways to set the duration. 
1. set on the global `<Toaster>` component
2. set on the `toast()` function

![CleanShot 2023-06-26 at 16 40 10](https://github.com/emilkowalski/sonner/assets/43137033/291ae05b-faf6-4777-a5d7-d5ef79a46001)

![CleanShot 2023-06-26 at 16 40 24](https://github.com/emilkowalski/sonner/assets/43137033/c4b8213c-ebf0-4644-bb0f-b247618033c4)

**Comment by emilkowalski** [comment]
You can set the duration per toast like @HananoshikaYomaru showed
