### ISSUE TITLE
Animations not working on Macbook

### ISSUE THREAD

**Issue by jessielaf** [emilkowalski/sonner#96]
Hi! I was trying the svelte port, but the animations were not working. I checked this library, and I had the same problem. See https://github.com/wobsoriano/svelte-sonner/issues/1

**Comment by emilkowalski** [comment]
Which browser and macOS version are you using?

**Comment by jessielaf** [comment]
@emilkowalski I tried it on ARC (Chromium based) and Safari

**Comment by jessielaf** [comment]
@emilkowalski yes I do. When turning this off, the animation starts again. I did not know this had an effect on browser functionality.
